/**
 * FaithLight i18n — Central translation loader
 * Locale data is inlined to avoid JSON import resolution issues.
 */

const en = {
   common: { read:"Read",share:"Share",save:"Save",search:"Search",generate:"Generate",tryAgain:"Try Again",loading:"Loading...",copy:"Copy",copied:"Copied!",saving:"Saving...",searching:"Searching...",close:"Close",cancel:"Cancel",confirm:"Confirm",delete:"Delete",edit:"Edit",back:"Back",next:"Next",done:"Done",yes:"Yes",no:"No",submit:"Submit",learnMore:"Learn More",viewAll:"View All",seeMore:"See More",download:"Download",play:"Play",pause:"Pause",retry:"Try Again",listen:"Listen",audioFailed:"Audio playback failed",audioUnavailable:"Audio not available for this verse",bookmark:"Bookmark" },
   home: { greetingMorning:"Good Morning",greetingEvening:"Good Evening",greetingAfternoon:"Good Afternoon",subtitle:"Your daily walk with God",addPrayer:"Add Prayer",verseOfDay:"Verse of the Day",todaysScripture:"Today's Scripture",aiInsight:"AI Spiritual Insight",generateInsight:"Generate Insight",generatingInsight:"Generating insight...",dailyJournal:"Daily Journal",startWriting:"Start Writing",reflectionPrompt:"What does today's verse mean to you?",dailyReflection:"Daily Reflection",continueReading:"Continue Reading",readMore:"Read More",aiReflection:"AI Reflection of the Day",generateReflection:"Generate Reflection",generatingReflection:"Generating your reflection...",studyPlansDesc:"Continue your guided Bible journey",noVerses:"No verses available",tryAgain:"Please try again",prayerOfDay:"Prayer of the Day",streak:"Reading Streak",days:"days",welcomeBack:"Welcome back",todayReading:"Today's Reading",verseLoadingError:"Unable to load verse of the day. Please check your connection and try again." },
   navigation: { home:"Home",daily:"Daily",bible:"Bible",study:"Study Plans",goals:"Goals",audio:"Audio Bible",prayer:"Prayer",community:"Community",groups:"Groups",profile:"Profile",settings:"Settings",login:"Login",logout:"Logout",premium:"Premium",discover:"Discover",journal:"Journal",highlights:"Highlights",quiz:"Quiz",sermonBuilder:"Sermon Builder" },
   support: { title:"FaithLight Support",subtitle:"AI Help Assistant",greeting:"Hi! 👋 I'm the FaithLight Support Assistant.",intro:"How can I help you today? You can pick a common issue below or type your own question.",language:"Language",placeholder:"Describe your issue...",cantResolve:"Can't resolve it?",emailUs:"Email",issue:{pageNotLoading:"Page not loading",languageNotChanging:"Language not changing",aiResponseFailed:"AI response failed",quizNotWorking:"Quiz not working",audioBibleProblem:"Audio Bible problem",verseSharingProblem:"Verse sharing problem",somethingElse:"Something else"} },
  bibleReader: { title:"Bible Reader",selectBook:"Select Book",selectChapter:"Select Chapter",selectVerse:"Select Verse",translation:"Translation",chapter:"Chapter",verse:"Verse",book:"Book",previousChapter:"Previous Chapter",nextChapter:"Next Chapter",highlight:"Highlight",addNote:"Add Note",copyVerse:"Copy Verse",shareVerse:"Share Verse",bookmark:"Bookmark",explainVerse:"Explain This Verse",compareTranslations:"Compare Translations",listenAudio:"Listen to Audio",fontSize:"Font Size",theme:"Theme",offlineAvailable:"Available Offline",downloadChapter:"Download Chapter",searchVerses:"Search Verses",oldTestament:"Old Testament",newTestament:"New Testament" },
  aiBibleCompanion: { title:"AI Bible Companion",subtitle:"Ask anything about Scripture",placeholder:"Ask a question about the Bible...",suggestedQuestions:"Suggested Questions",thinking:"Thinking...",error:"We could not get a response right now. Please try again in a moment.",copyResponse:"Copy Response",newConversation:"New Conversation",disclaimer:"AI responses are for study purposes. Always verify with Scripture." },
  aiEnhancedBibleStudy: { title:"AI Enhanced Bible Study",studyPlan:"Study Plan",passageSummary:"Passage Summary",theology:"Theological Insights",generatePlan:"Generate Study Plan",analyzePassage:"Analyze Passage",exploreTheology:"Explore Theology",topicPlaceholder:"Enter a topic or theme...",passagePlaceholder:"Enter a Bible reference (e.g. John 3:16)...",theologyPlaceholder:"Enter a theological concept...",generating:"Generating...",dayLabel:"Day",readingLabel:"Reading",reflectionLabel:"Reflection" },
  quiz: { title:"Daily Quiz",startQuiz:"Start Quiz",nextQuestion:"Next Question",submitAnswer:"Submit Answer",score:"Score",correct:"Correct!",incorrect:"Incorrect",explanation:"Explanation",tryAgain:"Try Again",completed:"Quiz Completed!",question:"Question",of:"of",yourScore:"Your Score",leaderboard:"Leaderboard",dailyChallenge:"Daily Challenge",xpEarned:"XP Earned" },
  dailyDevotional: { title:"Daily Devotional",subtitle:"A verse and reflection to inspire your day",loading:"Loading today's verse...",verseNotFound:"Verse Not Found",verseNotFoundDesc:"Could not load the Bible verse. Please try again later.",reflectAndPray:"Reflect & Pray",reflect1:"How does this verse speak to your life today?",reflect2:"What action can you take based on this truth?",reflect3:"Take a moment to pray about what you've learned." },
  journal: { title:"Daily Journal",todaysVerse:"Today's verse",placeholder:"Write your reflection on today's verse...",chars:"chars",saved:"Saved!",saveEntry:"Save Entry",newEntry:"New Entry",myEntries:"My Entries",noEntries:"No journal entries yet",startJournal:"Start your journal",mood:"How are you feeling?",grateful:"Grateful",hopeful:"Hopeful",peaceful:"Peaceful",joyful:"Joyful",challenged:"Challenged",questioning:"Questioning" },
  audioBible: { title:"Audio Bible",nowPlaying:"Now Playing",playbackSpeed:"Playback Speed",downloadForOffline:"Download for Offline",downloaded:"Downloaded",downloading:"Downloading...",playlist:"Playlist",addToPlaylist:"Add to Playlist",autoPlay:"Auto-Play",sleepTimer:"Sleep Timer",rewind:"Rewind 15s",fastForward:"Forward 15s",chapterComplete:"Chapter Complete",listeningProgress:"Listening Progress" },
  prayer: { title:"Prayer Wall",myJournal:"My Journal",newRequest:"New Prayer Request",prayForThis:"Pray for This",praying:"Praying...",prayed:"I Prayed",prayerCount:"people praying",anonymous:"Anonymous",streak3:"3-Day Streak!",streak7:"7-Day Streak!",streak30:"30-Day Streak!",streakMessage3:"You're building momentum!",streakMessage7:"A week of devotion!",streakMessage30:"An entire month!",categories:{health:"Health",family:"Family",work:"Work",faith:"Faith",relationships:"Relationships",finances:"Finances",other:"Other"},status:{active:"Active",answered:"Answered",archived:"Archived"} },
  settings: { title:"Settings",language:"Language",selectLanguage:"Select Language",theme:"Theme",fontSize:"Font Size",notifications:"Notifications",dailyVerse:"Daily Verse Reminder",prayerReminder:"Prayer Reminder",offlineStorage:"Offline Storage",account:"Account",deleteAccount:"Delete Account",privacyPolicy:"Privacy Policy",termsOfUse:"Terms of Use",about:"About FaithLight",version:"Version",logout:"Logout",saveSettings:"Save Settings",settingsSaved:"Settings saved!" },
  legal: { privacy:{title:"Privacy Policy",s1:"Information We Collect",s2:"How We Use Your Information",s3:"Data Storage",s4:"Third-Party Services",s5:"Contact"},terms:{title:"Terms of Use",s1:"Purpose of the App",s2:"Acceptable Use",s3:"Intellectual Property",s4:"AI Features",s5:"Limitation of Liability"},deletion:{title:"Data Deletion Request",subtitle:"You have the right to request deletion of your personal data.",s1:"What Gets Deleted",s2:"How to Request Deletion",s3:"Processing Time",submit:"Submit Deletion Request",confirm:"I understand this action is permanent and cannot be undone.",success:"Your deletion request has been received. We will process it within 30 days."},lastUpdated:"Last Updated" },
  offline: { title:"Offline Library",downloadBooks:"Download Books for Offline",cacheStats:"Offline Storage",chapters:"chapters",downloadProgress:"Download Progress",clearCache:"Clear All Cache",confirmClear:"Clear all cached Bible content?",info:"Download entire Bible books to read offline.",available:"Available Offline",notAvailable:"Not Available Offline",downloading:"Downloading...",downloadComplete:"Download Complete" },
  errors: { generic:"Something went wrong. Please try again.",network:"Network error. Please check your connection.",notFound:"Page not found.",authRequired:"Please sign in to continue.",premiumRequired:"This feature requires a Premium subscription.",aiUnavailable:"AI service is temporarily unavailable.",loadFailed:"Failed to load content.",saveFailed:"Failed to save. Please try again." },
  glossary: { book:"Book",chapter:"Chapter",verse:"Verse",search:"Search",studyPlan:"Study Plan",insight:"Insight",summary:"Summary",question:"Question",answer:"Answer",save:"Save",share:"Share" },
  studyRooms: { title:"Study Rooms",subtitle:"Join believers to study, discuss, and grow together.",searchPlaceholder:"Search rooms",filters:{all:"All",myRooms:"My Rooms",public:"Public",private:"Private"},createButton:"Create Room",join:"Join",open:"Open",invite:"Invite",emptyTitle:"No study rooms yet",emptyText:"Create the first room and invite others to study together." },
  createRoom: { title:"Create Study Room",name:"Room Name",description:"Description",language:"Language",category:"Category",privacy:"Privacy",public:"Public",private:"Private",inviteCode:"Invite Code",maxMembers:"Maximum Members",allowPrayerRequests:"Allow Prayer Requests",allowVerseSharing:"Allow Verse Sharing",allowAISummaries:"Allow AI Summaries",cancel:"Cancel",submit:"Create Room" },
  studyPlan: { title:"Personalized Bible Study Plan",subtitle:"Tell us what you're going through. We'll build a plan just for you.",aiPowered:"AI-Powered Study Plans",generateMyPlan:"Generate My Plan",buildingPlan:"Building your study plan…",mySavedPlans:"My Saved Plans",myStudyPlans:"My Study Plans",newPlan:"New Plan",noSavedPlans:"No saved plans yet.",saveStartPlan:"Save & Start This Plan",complete:"🎉 Plan complete!",reflection:"✍ Reflection",completeDay:"Complete Day",markIncomplete:"Mark Incomplete",whatAreYouGoingThrough:"What are you going through?",planLength:"Plan length",other:"Other…",customPlaceholder:"Describe what you're going through…" },
  challenge: { anxiety:"Dealing with Anxiety",purpose:"Finding Purpose",fear:"Overcoming Fear",grief:"Grief & Loss",faith:"Strengthening Faith",forgiveness:"Forgiving Others",marriage:"Marriage & Relationships",financial:"Financial Stress",loneliness:"Loneliness",addiction:"Addiction & Temptation",doubt:"Doubt & Questions",prayer:"Growing in Prayer" },
  common_days: { days_3:"3 Days",days_7:"7 Days",days_14:"14 Days",days_30:"30 Days" },
  room: { chatTab:"Chat",versesTab:"Verses",prayerTab:"Prayer",aboutTab:"About",messagePlaceholder:"Write a message",shareVerse:"Share Verse",addPrayerRequest:"Add Prayer Request",praying:"Praying" },
  };

const om = {
   common: { read:"Dubbisi",share:"Qoodi",save:"Olkaa'i",search:"Barbaadi",generate:"Uumi",tryAgain:"Irra Deebi'i Yaali",loading:"Fe'aa jira...",copy:"Qoqodhi",copied:"Qoqodhame!",saving:"Kuuse jira...",searching:"Barbaadha jira...",close:"Cufuu",cancel:"Dhiisi",confirm:"Mirkaneessi",delete:"Haqi",edit:"Gulaali",back:"Deebi'i",next:"Itti aanu",done:"Xumurame",yes:"Eeyyee",no:"Lakkii",submit:"Galchi",learnMore:"Dabalata Baradhu",viewAll:"Hunda Ilaali",seeMore:"Dabalata Ilaali",download:"Buufadhu",play:"Taphadhu",pause:"Dhaabi",retry:"Irra Deebi'i",listen:"Dhaggeeffadhu",audioFailed:"Taphannaan sagalee hin milkoofne",audioUnavailable:"Sagaleen ayaata kanaaf amma hin argamne",bookmark:"Milikkita Godhi" },
   navigation: { home:"Mana",daily:"Guyyaa",bible:"Macaafa Qulqulluu",study:"Karoora Barnootaa",goals:"Kaayyoo",audio:"Macaafa Qulqulluu Sagalee",prayer:"Kadhannaa",community:"Hawaasa",groups:"Garee",profile:"Profaayilii",settings:"Qindaa'ina",login:"Seeni",logout:"Ba'i",premium:"Premium",discover:"Safaruu",journal:"Yaadannoo",highlights:"Ifa Godhamtoota",quiz:"Qormaata",sermonBuilder:"Uumaa Lallabaa" },
   home: { greetingMorning:"Akkam Bulte",greetingEvening:"Akkam Oolte",greetingAfternoon:"Akkam Teette",subtitle:"Imala kee guyyaa guyyaan Waaqayyo wajjin",addPrayer:"Kadhannaa Dabali",verseOfDay:"Ayaata Guyyaa",todaysScripture:"Ayaata har'aa",aiInsight:"Hubannoo AI",generateInsight:"Hubannoo Uumi",generatingInsight:"Hubannoo uumaa jira...",dailyJournal:"Yaadannoo Guyyaa",startWriting:"Barreessuu Jalqabi",reflectionPrompt:"Ayaatni har'aa inumakaa maali?",dailyReflection:"Yaaduu Guyyaa",continueReading:"Dubbisuu Itti Fufi",readMore:"Dabalata Dubbisi",aiReflection:"Yaaduu AI Guyyaa",generateReflection:"Yaaduu Uumi",generatingReflection:"Yaaduu kee uumaa jira...",studyPlansDesc:"Imala macaaba kee qajeelfamaa itti fufi",noVerses:"Ayaatni hin jiru",tryAgain:"Irra deebi'i",prayerOfDay:"Kadhannaa Guyyaa",streak:"Itti Fufuu Dubbisuu",days:"guyyaa",welcomeBack:"Baga Deebitee",todayReading:"Dubbisa Har'aa",verseLoadingError:"Ayaata guyyaa fe'uu hin dandeenye. Walqunnamtii kee mirkaneessi fi irra deebi'i yaali." },
   support: { title:"Gargaarsa FaithLight",subtitle:"Gargaaraa AI",greeting:"Akkam! 👋 Ani Gargaaraa FaithLight AI dha.",intro:"Har'a akkamitti si gargaaruu danda'a? Rakkoo keessaa tokko filachuu dandeessa yookaan gaaffii kee barreessuu dandeessa.",language:"Afaan",placeholder:"Rakkoo kee ibsi...",cantResolve:"Furmaata hin argannee?",emailUs:"Imeelii",issue:{pageNotLoading:"Fuulni hin banamu",languageNotChanging:"Afaan hin jijjiiramu",aiResponseFailed:"Deebiin AI fashale",quizNotWorking:"Quiz hin hojjetu",audioBibleProblem:"Rakkoo Macaafa sagalee",verseSharingProblem:"Rakkoo qoodinsa caqasaa",somethingElse:"Kan biraa"} },
  bibleReader: { title:"Dubbisaa Macaafa Qulqulluu",selectBook:"Kitaaba Filadhu",selectChapter:"Boqonnaa Filadhu",selectVerse:"Ayaata Filadhu",translation:"Hiikkaa",chapter:"Boqonnaa",verse:"Ayaata",book:"Kitaaba",previousChapter:"Boqonnaa Duraa",nextChapter:"Boqonnaa Itti Aanu",highlight:"Ifa Godhi",addNote:"Yaada Dabalii",copyVerse:"Ayaata Qoqodhi",shareVerse:"Ayaata Qoodi",bookmark:"Boqonnaa Kaayyadhu",explainVerse:"Ayaata Ibsi",compareTranslations:"Hiikkaalee Walsigi",listenAudio:"Sagalee Dhaggeeffadhu",fontSize:"Bal'ina Barreeffama",theme:"Haala Mul'ataa",offlineAvailable:"Alaayinii Hin Barbaachifne",downloadChapter:"Boqonnaa Buufadhu",searchVerses:"Ayaatota Barbaadi",oldTestament:"Kakuu Moofaa",newTestament:"Kakuu Haaraa" },
  aiBibleCompanion: { title:"Hiriyaa AI Macaafa Qulqulluu",subtitle:"Waa'ee Caaffataa gaaffii kaasi",placeholder:"Macaafa Qulqulluu irratti gaaffii kaasi...",suggestedQuestions:"Gaaffilee Gorsamoo",thinking:"Yaadaa jira...",error:"Ibsi Afaan Oromootiin amma hin argamne. Mee irra deebi'ii yaali.",copyResponse:"Deebii Qoqodhi",newConversation:"Haasawaa Haaraa",disclaimer:"Deebiin AI qo'annoof malee. Yeroo hundaa Caaffataan mirkaneessi." },
  aiEnhancedBibleStudy: { title:"Qo'annoo Macaafa Qulqulluu AI",studyPlan:"Karoora Qo'annoo",passageSummary:"Cuunfaa Kutaa",theology:"Hubannoo Barnoota Amantii",generatePlan:"Karoora Qo'annoo Uumi",analyzePassage:"Kutaa Xiinxali",exploreTheology:"Barnoota Amantii Qoradhu",topicPlaceholder:"Mata duree ykn dhimma galchi...",passagePlaceholder:"Wabii Macaafa Qulqulluu galchi (fkn. Yoh 3:16)...",theologyPlaceholder:"Yaada barnoota amantii galchi...",generating:"Uumaa jira...",dayLabel:"Guyyaa",readingLabel:"Dubbisa",reflectionLabel:"Yaaduu" },
  dailyDevotional: { title:"Kadhannaa Guyyaa",subtitle:"Lakkoofsa fi xiinxala guyyaa kee si jajjabeessu",loading:"Caqasa har'aa fe'aa jira...",verseNotFound:"Caqasni Hin Argamne",verseNotFoundDesc:"Caqasa Macaafa Qulqulluu fe'uu hin dandeenye. Mee irra deebi'ii yaali.",reflectAndPray:"Yaadii fi Kadhadhu",reflect1:"Caqasni kun guyyaa har'aa jireenyakee irratti maal dubba?",reflect2:"Dhugaa kana irratti hundaa'uudhaan maal gochuu dandeessa?",reflect3:"Waa'ee waan baratteef mee yeroo tokko kadhadhu." },
  quiz: { title:"Qormaata Guyyaa",startQuiz:"Qormaata Jalqabi",nextQuestion:"Gaaffii Itti Aanu",submitAnswer:"Deebii Galchi",score:"Qabxii",correct:"Sirrii dha!",incorrect:"Sirrii miti",explanation:"Ibsa",tryAgain:"Irra Deebi'i Yaali",completed:"Qormaati Xumurameera!",question:"Gaaffii",of:"keessaa",yourScore:"Qabxii Kee",leaderboard:"Tartiiba Sadarkaa",dailyChallenge:"Carraa Guyyaa",xpEarned:"XP Argame" },
  journal: { title:"Yaadannoo Guyyaa",todaysVerse:"Ayaata har'aa",placeholder:"Luqqisa har'a irratti yaada kee barreessi...",chars:"caasimaa",saved:"Kuufatame!",saveEntry:"Galcha Kuufi",newEntry:"Galcha Haaraa",myEntries:"Galchoota Koo",noEntries:"Yaadannoon hin jiru",startJournal:"Yaadannoo jalqabi",mood:"Akkam jirta?",grateful:"Galateeffadha",hopeful:"Abdii qaba",peaceful:"Nagaa qaba",joyful:"Gammada",challenged:"Rakkoo qaba",questioning:"Gaafachaa jira" },
  audioBible: { title:"Macaafa Qulqulluu Sagalee",nowPlaying:"Amma Taphachaa jira",playbackSpeed:"Saffisa Taphataa",downloadForOffline:"Alaayinii Maaf Buufadhu",downloaded:"Buufatame",downloading:"Buufachaa jira...",playlist:"Tarree Taphataa",addToPlaylist:"Tarreetti Dabalii",autoPlay:"Ofumaan Taphadhu",sleepTimer:"Yeroo Hirriba",rewind:"15dqq Deebi'i",fastForward:"15dqq Darbii",chapterComplete:"Boqonnaan Xumurame",listeningProgress:"Cimaa Dhaggeeffachuu" },
  prayer: { title:"Gaara Kadhannaa",myJournal:"Yaadannoo Koo",newRequest:"Kadhannaa Haaraa",prayForThis:"Kanaaf Kadhadhu",praying:"Kadhachaa jira...",prayed:"Kadhadhe",prayerCount:"namni kadhachaa jiru",anonymous:"Maqaa malee",categories:{health:"Fayyaa",family:"Maatii",work:"Hojii",faith:"Amantii",relationships:"Haasawaa",finances:"Faayinaansii",other:"Kan biraa"},status:{active:"Hojjachaa jira",answered:"Deebii argame",archived:"Kuufame"} },
  settings: { title:"Qindaa'ina",language:"Afaan",selectLanguage:"Afaan Filadhu",theme:"Haala Mul'ataa",fontSize:"Bal'ina Barreeffama",notifications:"Beeksisa",dailyVerse:"Yaadachiisa Ayaata Guyyaa",prayerReminder:"Yaadachiisa Kadhannaa",offlineStorage:"Kuusaa Alaayinii",account:"Herrega",deleteAccount:"Herrega Haqi",privacyPolicy:"Imaammata Iccitii",termsOfUse:"Haala Fayyadamaa",about:"Waa'ee FaithLight",version:"Versiinii",logout:"Ba'i",saveSettings:"Qindaa'ina Kuufi",settingsSaved:"Qindaa'inni kuufatame!" },
  legal: { privacy:{title:"Imaammata Iccitii",s1:"Odeeffannoo Nuti Walitti Qabnu",s2:"Akkaataa Odeeffannoo Keessan Fayyadamnu",s3:"Kuusaa Odeeffannoo",s4:"Tajaajila Qaama Sadaffaa",s5:"Qunnamtii"},terms:{title:"Haala Fayyadamaa",s1:"Kaayyoo Appii",s2:"Fayyadama Sirrii",s3:"Qabeenya Sammuu",s4:"Tajaajila AI",s5:"Daangaa Itti Gaafatamummaa"},deletion:{title:"Gaaffii Haqa Odeeffannoo",subtitle:"Odeeffannoo dhuunfaa kee haqa gaafachuu mirga qabda.",s1:"Maal Haqama",s2:"Akkaataa Gaaffii Dhiyeessuu",s3:"Yeroo Hojii Irra Ooluu",submit:"Gaaffii Haqa Galchi",confirm:"Kun deebi'uu hin dandeenye ta'uu hubadha.",success:"Gaaffiin haqa kee fudhatamuudhaan guyyaa 30 keessatti hojjetama."},lastUpdated:"Yeroo Dhumaa Haaromame" },
  offline: { title:"Maktaba Alaayinii",downloadBooks:"Kitaabota Alaayinii Maaf Kuufi",cacheStats:"Dirmaata Alaayinii",chapters:"boqonnaa",downloadProgress:"Cimaa Kuufuu",clearCache:"Boba Hir Hir",confirmClear:"Boba qabeentoota Macaaba hir hir jedhi?",info:"Kitaabota Macaaba guutuu kuufi alaayinii dhaagee.",available:"Alaayinii Jira",notAvailable:"Alaayinii Hin Jiru",downloading:"Buufachaa jira...",downloadComplete:"Buufachuun Xumurame" },
  errors: { generic:"Rakkoo tokko uumame. Irra deebi'i yaali.",network:"Rakkoo Interneetii. Walqunnamtii kee mirkaneessi.",notFound:"Fuula hin argamne.",authRequired:"Itti fufuuf seeni.",premiumRequired:"Tajaajilni kun Premium gaafata.",aiUnavailable:"Tajaajilli AI amma hin jiru.",loadFailed:"Qabiyyee fe'uu hin dandeenye.",saveFailed:"Kuufachuu hin dandeenye. Irra deebi'i yaali." },
  glossary: { book:"Kitaaba",chapter:"Boqonnaa",verse:"Ayaata",search:"Barbaadi",studyPlan:"Karoora Barnootaa",insight:"Hubannoo",summary:"Cuunfaa",question:"Gaaffii",answer:"Deebii",save:"Olkaa'i",share:"Qoodi" },
  studyRooms: { title:"Kutaa Qo'annoo",subtitle:"Walitti makamanii Macaafa Qulqulluu qo'adhaa, mari'adhaa, keessaa guddadhaa.",searchPlaceholder:"Kutaa barbaadi",filters:{all:"Hunda",myRooms:"Kutaalee Koo",public:"Ifaa",private:"Dhuunfaa"},createButton:"Kutaa Uumi",join:"Seeni",open:"Bani",invite:"Afeerii",emptyTitle:"Kutaan qo'annoo hin jiru",emptyText:"Kutaa jalqabaa uumii namoota kaan afeeri." },
  createRoom: { title:"Kutaa Qo'annoo Uumi",name:"Maqaa Kutaa",description:"Ibsa",language:"Afaan",category:"Gosa",privacy:"Dhuunfummaa",public:"Ifaa",private:"Dhuunfaa",inviteCode:"Koodii Afeerii",maxMembers:"Baay'ina Miseensotaa",allowPrayerRequests:"Gaaffii Kadhannaa Hayyami",allowVerseSharing:"Qoodinsa Caqasaa Hayyami",allowAISummaries:"Cuunfaa AI Hayyami",cancel:"Dhiisi",submit:"Kutaa Uumi" },
  studyPlan: { title:"Karoora Qo'annoo Dhuunfaa",subtitle:"Maal keessa jirta? Karaa kee ijaaraa.",aiPowered:"Karoorota AI",generateMyPlan:"Karoora Koo Uumi",buildingPlan:"Karoora qo'annoo kee ijaaraa…",mySavedPlans:"Karoorota Kuufaman",myStudyPlans:"Karoorota Qo'annoo Koo",newPlan:"Karoora Haaraa",noSavedPlans:"Karooran kuufame hin jiru.",saveStartPlan:"Kuufi fi Jalqabi",complete:"🎉 Xumurame!",reflection:"✍ Yaaduu",completeDay:"Guyyaa Xumuri",markIncomplete:"Hin Xumuramin jechuu",whatAreYouGoingThrough:"Maal keessa jirta?",planLength:"Dheerina Karoora",other:"Kan biraa…",customPlaceholder:"Maal keessa jirta ibsi…" },
  challenge: { anxiety:"Yaaddoo waliin jiraachuu",purpose:"Kaayyoo barbaaduu",fear:"Sodaa injifachuu",grief:"Gaddaa fi Dhabuu",faith:"Amantii jabaachu",forgiveness:"Namoota Dhiifuu",marriage:"Heeruma fi Walitti dhufeenya",financial:"Rakko Maallaqaa",loneliness:"Addaa bahuudhaan jiraachuu",addiction:"Qorichaafi Qormaata",doubt:"Shakki fi Gaaffilee",prayer:"Kadhannaa keessatti guddachuu" },
  room: { chatTab:"Marii",versesTab:"Caqasoota",prayerTab:"Kadhannaa",aboutTab:"Waa'ee",messagePlaceholder:"Ergaa barreessi",shareVerse:"Caqasa Qoodi",addPrayerRequest:"Gaaffii Kadhannaa Dabaluu",praying:"Kadhachaa Jira" },
  };

const am = {
   common: { read:"አንብብ",share:"አጋራ",save:"አስቀምጥ",search:"ፈልግ",generate:"ፍጠር",tryAgain:"እንደገና ሞክር",loading:"በመጫን ላይ...",copy:"ቅዳ",copied:"ተቀድቷል!",saving:"ማስቀመጥ...",searching:"ፍለጋ ላይ...",close:"ዝጋ",cancel:"ሰርዝ",confirm:"አረጋግጥ",delete:"ሰርዝ",edit:"አርትዕ",back:"ተመለስ",next:"ቀጣይ",done:"ተጠናቋል",yes:"አዎ",no:"አይ",submit:"አስገባ",learnMore:"ተጨማሪ ይወቁ",viewAll:"ሁሉንም ይዩ",seeMore:"ተጨማሪ ይዩ",download:"አውርድ",play:"አጫውት",pause:"አቁም",retry:"እንደገና ሞክር" },
   navigation: { home:"መነሻ",daily:"ዕለታዊ",bible:"መጽሐፍ ቅዱስ",study:"የጥናት እቅድ",goals:"ግቦች",audio:"የድምፅ መጽሐፍ ቅዱስ",prayer:"ጸሎት",community:"ማህበረሰብ",groups:"ቡድኖች",profile:"መገለጫ",settings:"ቅንብሮች",login:"ግባ",logout:"ውጣ",premium:"ፕሬሚየም",discover:"ያግኙ",journal:"ማስታወሻ",highlights:"ጎላ ያሉ",quiz:"ሙከራ",sermonBuilder:"ስብከት ፈጣሪ" },
   home: { greetingMorning:"እንደምን አደሩ",greetingEvening:"እንደምን አመሹ",greetingAfternoon:"እንደምን ዋሉ",subtitle:"ዛሬ በእምነት ውስጥ እደጉ",verseOfDay:"የቀኑ ጥቅስ",todaysScripture:"የዛሬ ቃል",aiInsight:"የAI ግንዛቤ",generateInsight:"ግንዛቤ ፍጠር",generatingInsight:"ግንዛቤ እየፈጠረ...",dailyJournal:"ዕለታዊ ማስታወሻ",startWriting:"መጻፍ ጀምር",reflectionPrompt:"የዛሬ ቃል ምን ይነግርዎታል?",dailyReflection:"ዕለታዊ ማሰብስ",continueReading:"ማንበብ ቀጥሉ",readMore:"ተጨማሪ ያንብቡ",aiReflection:"የAI ዕለታዊ ማሰብስ",generateReflection:"ማሰብስ ፍጠር",generatingReflection:"ማሰብስ ሲፈጠር...",studyPlansDesc:"የሚመራ መጽሐፍ ቅዱስ ጉዞ ቀጥሉ",noVerses:"ምንም ቃልስ የለም",tryAgain:"እንደገና ሞክር",prayerOfDay:"የቀኑ ጸሎት",streak:"ተከታታይ ንባብ",days:"ቀናት",welcomeBack:"እንኳን ደህና መጡ",todayReading:"የዛሬ ንባብ" },
   support: { title:"የFaithLight ድጋፍ",subtitle:"AI እገዛ ረዳት",greeting:"ሰላም! 👋 ከFaithLight ድጋፍ ረዳት ነኝ።",intro:"ዛሬ እንዴት እሳተፍ ይችላለሁ? ከዚህ በታች የተለመዱ ጉዳዮችን መምረጥ ወይም የራስዎን ጥያቄ መተየብ ይችላሉ።",language:"ቋንቋ",placeholder:"ችግርዎን ይግለጹ...",cantResolve:"ሊፈታ አልቻለ?",emailUs:"ኢሜል",issue:{pageNotLoading:"ገጹ ሊገኝ አልቻለ",languageNotChanging:"ቋንቋ ነቅጥ አልቻለ",aiResponseFailed:"የAI ምላሽ ወድቋል",quizNotWorking:"ሙከራ ሊሰራ አልቻለ",audioBibleProblem:"የድምፅ መጽሐፍ ቅዱስ ችግር",verseSharingProblem:"ጥቅስ ማጋራት ችግር",somethingElse:"ሌላ ነገር"} },
  bibleReader: { title:"መጽሐፍ ቅዱስ አንባቢ",selectBook:"መጽሐፍ ይምረጡ",selectChapter:"ምዕራፍ ይምረጡ",selectVerse:"ቁጥር ይምረጡ",translation:"ትርጉም",chapter:"ምዕራፍ",verse:"ጥቅስ",book:"መጽሐፍ",previousChapter:"ቀዳሚ ምዕራፍ",nextChapter:"ቀጣይ ምዕራፍ",highlight:"ጎላ አድርግ",addNote:"ማስታወሻ ጨምር",copyVerse:"ጥቅስ ቅዳ",shareVerse:"ጥቅስ አጋራ",bookmark:"ምልክት ይስጡ",explainVerse:"ጥቅሱን አብራራ",compareTranslations:"ትርጉሞችን አወዳድር",listenAudio:"ድምፅ ያዳምጡ",fontSize:"የፊደል መጠን",theme:"ገጽታ",offlineAvailable:"ከኢንተርኔት ውጭ ይገኛል",downloadChapter:"ምዕራፍ አውርድ",searchVerses:"ጥቅሶችን ፈልግ",oldTestament:"ብሉይ ኪዳን",newTestament:"አዲስ ኪዳን" },
  aiBibleCompanion: { title:"የAI መጽሐፍ ቅዱስ ጓደኛ",subtitle:"ስለ ቅዱሳን ጽሑፎች ጠይቁ",placeholder:"ስለ መጽሐፍ ቅዱስ ጥያቄ ያቅርቡ...",suggestedQuestions:"የሚጠቁሙ ጥያቄዎች",thinking:"በማሰብ ላይ...",error:"አሁን መልስ ማግኘት አልቻልንም። እባክዎ ቆይተው እንደገና ይሞክሩ።",copyResponse:"መልሱን ቅዳ",newConversation:"አዲስ ውይይት",disclaimer:"የAI ምላሾች ለጥናት ዓላማ ናቸው። ሁልጊዜ በቅዱሳን ጽሑፎች ያረጋግጡ።" },
  aiEnhancedBibleStudy: { title:"የAI የተሻሻለ የመጽሐፍ ቅዱስ ጥናት",studyPlan:"የጥናት እቅድ",passageSummary:"የምንባብ ማጠቃለያ",theology:"የሥነ-መለኮት ግንዛቤ",generatePlan:"የጥናት እቅድ ፍጠር",analyzePassage:"ምንባቡን ተንተን",exploreTheology:"ሥነ-መለኮትን ዳስስ",topicPlaceholder:"ርዕስ ወይም ጭብጥ ያስገቡ...",passagePlaceholder:"የመጽሐፍ ቅዱስ ማጣቀሻ ያስገቡ (ለምሳ. ዮሐ 3:16)...",theologyPlaceholder:"የሥነ-መለኮት ጽንሰ-ሐሳብ ያስገቡ...",generating:"እየፈጠረ...",dayLabel:"ቀን",readingLabel:"ንባብ",reflectionLabel:"ማሰብስ" },
  dailyDevotional: { title:"ዕለታዊ ጸሎት",subtitle:"ዛሬዎን ለማነሳሳት ቁጥር እና ማሰብስ",loading:"የዛሬ ቁጥር እየጫነ...",verseNotFound:"ቁጥሩ አልተገኘም",verseNotFoundDesc:"የመጽሐፍ ቅዱስ ቁጥሩ ማምጣት አልቻለም። እባክዎ ቆይተው እንደገና ይሞክሩ።",reflectAndPray:"ሲያስቡ እና ሲጸልዩ",reflect1:"ይህ ቁጥር ዛሬ ሕይወትዎ ላይ ምን ይናገራል?",reflect2:"ከዚህ እውነት ላይ ተመርኩዘው ምን ድርጊት መወሰድ ይችላሉ?",reflect3:"ስለ ተማሩት ነገር ትንሽ ጊዜ ወስደው ጸልዩ።" },
  quiz: { title:"ዕለታዊ ሙከራ",startQuiz:"ሙከራ ጀምር",nextQuestion:"ቀጣይ ጥያቄ",submitAnswer:"መልስ አስገባ",score:"ውጤት",correct:"ትክክል!",incorrect:"ትክክል አይደለም",explanation:"ማብራሪያ",tryAgain:"እንደገና ሞክር",completed:"ሙከራ ተጠናቅቋል!",question:"ጥያቄ",of:"ከ",yourScore:"ውጤትዎ",leaderboard:"የደረጃ ሰሌዳ",dailyChallenge:"ዕለታዊ ፈተና",xpEarned:"XP ተገኝቷል" },
  journal: { title:"ዕለታዊ ማስታወሻ",todaysVerse:"የዛሬ ቃል",placeholder:"ዛሬ በዚህ ቃል ላይ ያለዎትን አስተያየት ይጻፉ...",chars:"ፊደሎች",saved:"ተቀምጧል!",saveEntry:"ግቤት አስቀምጥ",newEntry:"አዲስ ግቤት",myEntries:"የኔ ግቤቶች",noEntries:"ምንም ማስታወሻ ግቤቶች የሉም",startJournal:"ማስታወሻ ጀምሩ",mood:"ስሜትዎ ምን ይመስላል?",grateful:"አመስጋኝ",hopeful:"ተስፋ ሞልቶ",peaceful:"ሰላም",joyful:"ደስተኛ",challenged:"ፈተና ላይ",questioning:"ጥያቄ ላይ" },
  audioBible: { title:"የድምፅ መጽሐፍ ቅዱስ",nowPlaying:"አሁን እየተጫወተ",playbackSpeed:"የማጫወቻ ፍጥነት",downloadForOffline:"ለኦፍላይን አውርድ",downloaded:"ወርዷል",downloading:"እያወረደ...",playlist:"የዘፈን ዝርዝር",addToPlaylist:"ወደ ዝርዝር ጨምር",autoPlay:"ራስ-ሰር አጫውት",sleepTimer:"የእንቅልፍ ሰዓት ቆጣሪ",rewind:"15 ሰከ ወደ ኋላ",fastForward:"15 ሰከ ወደ ፊት",chapterComplete:"ምዕራፍ ተጠናቋል",listeningProgress:"የማዳመጥ ሂደት" },
  prayer: { title:"የጸሎት ግድግዳ",myJournal:"የኔ ማስታወሻ",newRequest:"አዲስ የጸሎት ጥያቄ",prayForThis:"ለዚህ ጸልይ",praying:"እየጸለዩ...",prayed:"ጸለይሁ",prayerCount:"ሰዎች እየጸለዩ",anonymous:"ስም-አልባ",categories:{health:"ጤና",family:"ቤተሰብ",work:"ሥራ",faith:"እምነት",relationships:"ግንኙነቶች",finances:"ፋይናንስ",other:"ሌሎች"},status:{active:"ንቁ",answered:"ምላሽ ተሰጠ",archived:"መዝገብ ቤት"} },
  settings: { title:"ቅንብሮች",language:"ቋንቋ",selectLanguage:"ቋንቋ ይምረጡ",theme:"ገጽታ",fontSize:"የፊደል መጠን",notifications:"ማሳወቂያዎች",dailyVerse:"ዕለታዊ ቃል ማስታወሻ",prayerReminder:"የጸሎት ማስታወሻ",offlineStorage:"ኦፍላይን ማከማቻ",account:"መለያ",deleteAccount:"መለያ ሰርዝ",privacyPolicy:"የግላዊነት ፖሊሲ",termsOfUse:"የአጠቃቀም መመሪያ",about:"ስለ FaithLight",version:"ስሪት",logout:"ውጣ",saveSettings:"ቅንብሮች አስቀምጥ",settingsSaved:"ቅንብሮች ተቀምጠዋል!" },
  legal: { privacy:{title:"የግላዊነት ፖሊሲ",s1:"የምንሰበስበው መረጃ",s2:"መረጃዎን እንዴት እንጠቀማለን",s3:"የውሂብ ማከማቻ",s4:"የሶስተኛ ወገን አገልግሎቶች",s5:"መገናኛ"},terms:{title:"የአጠቃቀም መመሪያ",s1:"የመተግበሪያው ዓላማ",s2:"የተፈቀደ አጠቃቀም",s3:"የአእምሮ ንብረት",s4:"የAI ባህሪዎች",s5:"የተጠያቂነት ገደብ"},deletion:{title:"የውሂብ ስረዛ ጥያቄ",subtitle:"የግል ውሂብዎን ለመሰረዝ የመጠየቅ መብት አለዎት።",s1:"የሚሰረዘው ምንድን ነው",s2:"ጥያቄ እንዴት ማቅረብ እንደሚቻል",s3:"የሂደት ጊዜ",submit:"የስረዛ ጥያቄ ያስገቡ",confirm:"ይህ ድርጊት ቋሚ ሲሆን ሊቀለበስ እንደማይችል ተረድቻለሁ።",success:"የስረዛ ጥያቄዎ ደርሷል። በ30 ቀናት ውስጥ እናስተናግደዋለን።"},lastUpdated:"በመጨረሻ የተሻሻለው" },
  offline: { title:"ኦፍላይን ቤተ-መጻሕፍት",downloadBooks:"ለኦፍላይን መጻሕፍት አውርድ",cacheStats:"ኦፍላይን ማከማቻ",chapters:"ምዕራፎች",downloadProgress:"የውርዶ ሂደት",clearCache:"ሁሉንም ካሽ ሰርዝ",confirmClear:"ሁሉም የተቀምጠ መጽሐፍ ቅዱስ ይሰረዝ?",info:"ሙሉ የመጽሐፍ ቅዱስ ምዕራፎችን አውርዱ ከኢንተርኔት ውጭ ያንብቡ።",available:"ኦፍላይን ይገኛል",notAvailable:"ኦፍላይን አይገኝም",downloading:"እያወረደ...",downloadComplete:"ውርዶ ተጠናቋል" },
  errors: { generic:"ችግር ተፈጠረ። እንደገና ሞክር።",network:"የኢንተርኔት ስህተት። ግንኙነቱን ያረጋግጡ።",notFound:"ገጹ አልተገኘም።",authRequired:"ለመቀጠል ይግቡ።",premiumRequired:"ይህ ባህሪ ፕሬሚየም ያስፈልጋል።",aiUnavailable:"የAI አገልግሎት ለጊዜው አይገኝም።",loadFailed:"ይዘቱን መጫን አልቻለም።",saveFailed:"ማስቀመጥ አልቻለም። እንደገና ሞክር።" },
  glossary: { book:"መጽሐፍ",chapter:"ምዕራፍ",verse:"ጥቅስ",search:"ፈልግ",studyPlan:"የጥናት እቅድ",insight:"ግንዛቤ",summary:"ማጠቃለያ",question:"ጥያቄ",answer:"መልስ",save:"አስቀምጥ",share:"አጋራ" },
  studyRooms: { title:"የጥናት ክፍሎች",subtitle:"ከአማኞች ጋር አንድ ሆነው ቅዱሳን ጽሑፎችን ለማጥናት ይተዋወቁ።",searchPlaceholder:"ክፍሎች ፈልግ",filters:{all:"ሁሉም",myRooms:"ውስጤ ክፍሎች",public:"ይፋ",private:"ግል"},createButton:"ክፍል ፍጠር",join:"ተጠቀም",open:"ክፈት",invite:"ግብዓት",emptyTitle:"ገና ምንም ጥናት ክፍሎች የሉም",emptyText:"የመጀመሪያውን ክፍል ፍጠር እና ሌሎችን አስጋብ።" },
  createRoom: { title:"ጥናት ክፍል ፍጠር",name:"ክፍል ስም",description:"መግለጫ",language:"ቋንቋ",category:"ምድብ",privacy:"ግላዊነት",public:"ይፋ",private:"ግል",inviteCode:"ግብዓት ኮድ",maxMembers:"ከፍተኛ አባላት",allowPrayerRequests:"ጸሎት ጥያቄዎችን ፍቀድ",allowVerseSharing:"ቁጥር ማጋራት ፍቀድ",allowAISummaries:"AI ማጠቃለያዎችን ፍቀድ",cancel:"ሰርዝ",submit:"ክፍል ፍጠር" },
  room: { chatTab:"ውይይት",versesTab:"ቁጥሮች",prayerTab:"ጸሎት",aboutTab:"ስለ",messagePlaceholder:"መልእክት ጻፍ",shareVerse:"ቁጥር ማጋራት",addPrayerRequest:"ጸሎት ጥያቄ ጨምር",praying:"ይጸልያል" },
  };

const ar = {
   common: { read:"اقرأ",share:"شارك",save:"احفظ",search:"ابحث",generate:"إنشاء",tryAgain:"حاول مرة أخرى",loading:"جاري التحميل...",copy:"نسخ",copied:"تم النسخ!",saving:"جاري الحفظ...",searching:"يتم البحث...",close:"أغلق",cancel:"إلغاء",confirm:"تأكيد",delete:"حذف",edit:"تعديل",back:"رجوع",next:"التالي",done:"تم",yes:"نعم",no:"لا",submit:"إرسال",learnMore:"اعرف المزيد",viewAll:"عرض الكل",seeMore:"مشاهدة المزيد",download:"تحميل",play:"تشغيل",pause:"إيقاف مؤقت",retry:"حاول مرة أخرى" },
   navigation: { home:"الرئيسية",daily:"يومي",bible:"الكتاب المقدس",prayer:"الصلاة",community:"المجتمع",settings:"الإعدادات",login:"تسجيل الدخول",logout:"تسجيل الخروج" },
   home: { greetingMorning:"صباح الخير",greetingEvening:"مساء الخير",greetingAfternoon:"مساء الخير",subtitle:"انمو في الإيمان اليوم",verseOfDay:"آية اليوم",todaysScripture:"الكتاب المقدس اليوم",aiInsight:"رؤى روحية من الذكاء الاصطناعي",generateInsight:"توليد الرؤى",generatingInsight:"جاري توليد الرؤى...",dailyJournal:"اليوميات اليومية",startWriting:"ابدأ الكتابة",reflectionPrompt:"ماذا تعني لك آية اليوم؟",dailyReflection:"التأمل اليومي",readMore:"اقرأ المزيد",aiReflection:"تأمل الذكاء الاصطناعي اليومي",generateReflection:"إنشاء تأمل",generatingReflection:"جاري إنشاء تأملك...",studyPlansDesc:"استمر في رحلتك الكتابية الموجهة",noVerses:"لا توجد آيات",tryAgain:"حاول مرة أخرى" },
   support: { title:"دعم FaithLight",subtitle:"مساعد الذكاء الاصطناعي",greeting:"مرحبا! 👋 أنا مساعد دعم FaithLight.",intro:"كيف يمكنني مساعدتك اليوم؟ يمكنك اختيار مشكلة شائعة أدناه أو اكتب سؤالك الخاص.",language:"اللغة",placeholder:"صف مشكلتك...",cantResolve:"لا يمكن حلها؟",emailUs:"البريد الإلكتروني",issue:{pageNotLoading:"الصفحة لا تحمل",languageNotChanging:"اللغة لا تتغير",aiResponseFailed:"فشل رد الذكاء الاصطناعي",quizNotWorking:"الاختبار لا يعمل",audioBibleProblem:"مشكلة في الكتاب المقدس الصوتي",verseSharingProblem:"مشكلة في مشاركة الآية",somethingElse:"شيء آخر"} },
   dailyDevotional: { title:"التأمل اليومي",subtitle:"آية وتأمل لإلهام يومك",loading:"جاري تحميل آية اليوم...",verseNotFound:"الآية غير موجودة",verseNotFoundDesc:"تعذر تحميل آية الكتاب المقدس. يرجى المحاولة مرة أخرى لاحقاً.",reflectAndPray:"تأمل وصلِّ",reflect1:"ماذا تقول لك هذه الآية في حياتك اليوم؟",reflect2:"ما الخطوة التي يمكنك اتخاذها بناءً على هذه الحقيقة؟",reflect3:"خذ لحظة للصلاة حول ما تعلمته." },
   journal: { title:"اليوميات اليومية",todaysVerse:"آية اليوم",placeholder:"اكتب انعكاساتك حول آية اليوم...",chars:"أحرف",saved:"تم الحفظ!" },
   studyRooms: { title:"غرف الدراسة",subtitle:"انضم للمؤمنين لدراسة وتناقش وتنمو معاً.",searchPlaceholder:"ابحث عن الغرف",filters:{all:"الكل",myRooms:"غرفي",public:"عام",private:"خاص"},createButton:"إنشاء غرفة",join:"انضم",open:"فتح",invite:"دعوة",emptyTitle:"لا توجد غرف دراسة بعد",emptyText:"أنشئ الغرفة الأولى وادعُ الآخرين للدراسة معك." },
   createRoom: { title:"إنشاء غرفة دراسة",name:"اسم الغرفة",description:"الوصف",language:"اللغة",category:"الفئة",privacy:"الخصوصية",public:"عام",private:"خاص",inviteCode:"رمز الدعوة",maxMembers:"الحد الأقصى للأعضاء",allowPrayerRequests:"السماح بطلبات الصلاة",allowVerseSharing:"السماح بمشاركة الآيات",allowAISummaries:"السماح بملخصات الذكاء الاصطناعي",cancel:"إلغاء",submit:"إنشاء غرفة" },
   room: { chatTab:"الدردشة",versesTab:"الآيات",prayerTab:"الصلاة",aboutTab:"حول",messagePlaceholder:"اكتب رسالة",shareVerse:"مشاركة الآية",addPrayerRequest:"إضافة طلب صلاة",praying:"يدعو" },
   errors: { generic:"حدث خطأ ما. يرجى المحاولة مرة أخرى.",network:"خطأ في الشبكة.",aiUnavailable:"خدمة الذكاء الاصطناعي غير متاحة مؤقتاً.",error:"لم نتمكن من الحصول على رد الآن. يرجى المحاولة مرة أخرى." },
};

const sw = {
  common: { read:"Soma",share:"Sambaza",save:"Hifadhi",search:"Tafuta",generate:"Tengeneza",tryAgain:"Jaribu Tena",loading:"Inapakia...",copy:"Nakili",copied:"Imenakiliwa!",saving:"Inahifadhi...",searching:"Inatafuta...",close:"Funga",cancel:"Ghairi",confirm:"Thibitisha",delete:"Futa",edit:"Hariri",back:"Rudi",next:"Ijayo",done:"Imekamilika",yes:"Ndiyo",no:"Hapana",submit:"Wasilisha",download:"Pakua",play:"Cheza",pause:"Simama",retry:"Jaribu Tena" },
  navigation: { home:"Nyumbani",daily:"Kila Siku",bible:"Biblia",prayer:"Sala",community:"Jamii",settings:"Mipangilio",login:"Ingia",logout:"Toka" },
  home: { greetingMorning:"Habari za asubuhi",greetingEvening:"Habari za jioni",subtitle:"Kukua katika imani leo",verseOfDay:"Aya ya Leo",todaysScripture:"Maandiko ya Leo",aiInsight:"Ufahamu wa Kiroho wa AI",generateInsight:"Tengeneza Ufahamu",generatingInsight:"Inatengeneza ufahamu...",dailyJournal:"Daftari la Kila Siku",startWriting:"Anza Kuandika",reflectionPrompt:"Aya ya leo ina maana gani kwako?",dailyReflection:"Tafakari ya Kila Siku",readMore:"Soma Zaidi",generateReflection:"Tengeneza Tafakari",generatingReflection:"Inatengeneza tafakari yako...",studyPlansDesc:"Endelea na safari yako ya Biblia iliyoongozwa",noVerses:"Hakuna aya",tryAgain:"Jaribu Tena" },
  dailyDevotional: { title:"Tafakari ya Kila Siku",subtitle:"Aya na tafakari kuhamasisha siku yako",loading:"Inapakia aya ya leo...",verseNotFound:"Aya Haikupatikana",verseNotFoundDesc:"Haikuweza kupakia aya ya Biblia. Tafadhali jaribu tena baadaye.",reflectAndPray:"Tafakari na Omba",reflect1:"Aya hii inasema nini katika maisha yako leo?",reflect2:"Hatua gani unaweza kuchukua kulingana na ukweli huu?",reflect3:"Chukua muda kusali kuhusu ulichojifunza." },
  journal: { title:"Daftari la Kila Siku",todaysVerse:"Aya ya Leo",placeholder:"Andika mawazo yako kuhusu aya ya leo...",chars:"herufi",saved:"Imehifadhiwa!" },
  studyRooms: { title:"Vyumba vya Masomo",subtitle:"Jiunga na waumini kujifunza, kujadiliana na kukua pamoja.",searchPlaceholder:"Tafuta vyumba",filters:{all:"Vyote",myRooms:"Vyumba Vyangu",public:"Umma",private:"Binafsi"},createButton:"Tengeneza Chumba",join:"Jiunga",open:"Fungua",invite:"Kamatia",emptyTitle:"Hakuna vyumba vya masomo bado",emptyText:"Tengeneza chumba la kwanza na kamatia watu wengine." },
  createRoom: { title:"Tengeneza Chumba cha Masomo",name:"Jina la Chumba",description:"Maelezo",language:"Lugha",category:"Jamii",privacy:"Uhifadhi",public:"Umma",private:"Binafsi",inviteCode:"Koди ya Kamatia",maxMembers:"Kiwango cha Juu cha Wanachama",allowPrayerRequests:"Ruhusu Maombi ya Sala",allowVerseSharing:"Ruhusu Kushiriki Ayati",allowAISummaries:"Ruhusu Muhtasari wa AI",cancel:"Ghairi",submit:"Tengeneza Chumba" },
  room: { chatTab:"Sehemu ya Mazungumzo",versesTab:"Ayati",prayerTab:"Sala",aboutTab:"Kuhusu",messagePlaceholder:"Andika ujumbe",shareVerse:"Shiriki Aya",addPrayerRequest:"Ongeza Ombi la Sala",praying:"Anasali" },
  errors: { generic:"Kitu fulani kimekwenda vibaya. Tafadhali jaribu tena.",network:"Hitilafu ya mtandao.",aiUnavailable:"Huduma ya AI haipatikani kwa sasa." },
  };

const ti = {
   common: { read:"ኣንብብ",share:"ካፍል",save:"ኣቐምጥ",search:"ደሊ",generate:"ፍጠር",tryAgain:"ደጊምካ ፈትን",loading:"ኣብ ምጽዓን...",copy:"ቅዳሕ",copied:"ቁዳሕ!",saving:"ኣብ ምቕዳሕ...",searching:"ኣብ ምድላይ...",close:"ዕጾ",cancel:"ሰርዝ",confirm:"ኣረጋግጽ",delete:"ሰርዝ",edit:"ኣርም",back:"ተመለስ",next:"ቀጺሉ",done:"ተፈጺሙ",yes:"እወ",no:"ኣይኮነን",submit:"ኣእቱ",download:"ኣውርድ",play:"ጽወት",pause:"ደው ኣብሎ",retry:"ደጊምካ ፈትን" },
   navigation: { home:"ቤት",daily:"ዕለታዊ",bible:"መጽሓፍ ቅዱስ",study:"መደብ ትምህርቲ",goals:"ዕላማታት",audio:"ድምጺ መጽሓፍ ቅዱስ",prayer:"ጸሎት",community:"ማሕበረሰብ",groups:"ጉጅለታት",profile:"ፕሮፋይል",settings:"ቅንብር",login:"እቶ",logout:"ውጻእ",premium:"ፕሪምዩም",discover:"ኣናዲ",journal:"ማስታወሻ",highlights:"ፍሉይ ነጥብታት",quiz:"ፈተና",sermonBuilder:"ሃናጺ ስብከት" },
   home: { greetingMorning:"ከመይ ሓደርኩም",greetingEvening:"ከመይ ኣመሸኩም",greetingAfternoon:"ከመይ ውዓልኩም",subtitle:"ሎሚ ብእምነት ዕበዩ",verseOfDay:"ቃል መዓልቲ",todaysScripture:"ናይ ሎሚ ጽሑፍ",aiInsight:"ናይ AI መንፈሳዊ ርድኢት",generateInsight:"ርድኢት ፍጠር",generatingInsight:"ርድኢት ኣብ ምፍጣር...",dailyJournal:"ዕለታዊ ማስታወሻ",startWriting:"ምጽሓፍ ጀምር",reflectionPrompt:"ናይ ሎሚ ቃል እንታይ ትርጉም ኣለዎ?",dailyReflection:"ዕለታዊ ኣስተንትኖ",readMore:"ተወሳኺ ኣንብብ",generateReflection:"ኣስተንትኖ ፍጠር",generatingReflection:"ኣስተንትኖ ኣብ ምፍጣር...",studyPlansDesc:"ዝምራሕ ጉዕዞ ናይ መጽሓፍ ቅዱስ ቀጽሎ",noVerses:"ቃላት የለን",tryAgain:"ደጊምካ ፈትን",streak:"ናይ ምንባብ ተኸታተልነት",days:"መዓልትታት",welcomeBack:"ብደሓን መጻእኩም",todayReading:"ናይ ሎሚ ንባብ" },
   support: { title:"ደገፍ FaithLight",subtitle:"ናይ AI ሓጋዚ ረዳኢ",greeting:"ሰላም! 👋 ናይ FaithLight ደገፍ ሓጋዚ እየ።",intro:"ሎሚ ብኸምይ ክሕግዘካ እኽእል? ካብ ታሕቲ ዘሎ ሓደ ጸገም ምረጽ ወይ ናትካ ሕቶ ጸሓፍ።",language:"ቋንቋ",placeholder:"ጸገምካ ግለጽ...",cantResolve:"ፍታሕ ዘይርካብ?",emailUs:"ኢሜይል",issue:{pageNotLoading:"ገጽ ኣይጽዓን",languageNotChanging:"ቋንቋ ኣይልወጥ",aiResponseFailed:"ናይ AI መልሲ ፈሺሉ",quizNotWorking:"ፈተና ኣይሰርሕ",audioBibleProblem:"ጸገም ናይ ድምጺ መጽሓፍ ቅዱስ",verseSharingProblem:"ጸገም ናይ ምካፋል ቃል",somethingElse:"ካልእ ነገር"} },
   bibleReader: { title:"ኣንባቢ መጽሓፍ ቅዱስ",selectBook:"መጽሓፍ ምረጽ",selectChapter:"ምዕራፍ ምረጽ",selectVerse:"ቃል ምረጽ",translation:"ትርጉም",chapter:"ምዕራፍ",verse:"ቃል",book:"መጽሓፍ",previousChapter:"ዝሓለፈ ምዕራፍ",nextChapter:"ዝቕጽል ምዕራፍ",highlight:"ፍሉይ ግበሮ",addNote:"ማስታወሻ ወሲኽ",copyVerse:"ቃል ቅዳሕ",shareVerse:"ቃል ካፍል",bookmark:"ምልክት ሃቦ",explainVerse:"ቃሉ ግለጽ",compareTranslations:"ትርጉማት ወዳደር",listenAudio:"ድምጺ ስምዕ",fontSize:"ዓቐን ፊደላት",theme:"ቅርጺ",offlineAvailable:"ብዘይ ኢንተርነት ይርከብ",downloadChapter:"ምዕራፍ ኣውርድ",searchVerses:"ቃላት ደሊ",oldTestament:"ኣሮን ኪዳን",newTestament:"ሓዲሽ ኪዳን" },
   quiz: { title:"ዕለታዊ ፈተና",startQuiz:"ፈተና ጀምር",nextQuestion:"ዝቕጽል ሕቶ",submitAnswer:"መልሲ ኣቐምጥ",score:"ነጥቢ",correct:"ቅኑዕ!",incorrect:"ቅኑዕ ኣይኮነን",tryAgain:"ደጊምካ ፈትን",completed:"ፈተና ተወዲኡ!",question:"ሕቶ",of:"ካብ",yourScore:"ናትካ ነጥቢ" },
   dailyDevotional: { title:"ዕለታዊ ጸሎት",subtitle:"ዛሬዎን ለማነሳሳት ቁጥር እና ማሰብስ",loading:"የዛሬ ቁጥር እየጫነ...",verseNotFound:"ቁጥሩ አልተገኘም",verseNotFoundDesc:"የመጽሐፍ ቅዱስ ቁጥሩ ማምጣት አልቻለም። እባክዎ ቆይተው እንደገና ይሞክሩ።",reflectAndPray:"ሲያስቡ እና ሲጸልዩ",reflect1:"ይህ ቁጥር ዛሬ ሕይወትዎ ላይ ምን ይናገራል?",reflect2:"ከዚህ እውነት ላይ ተመርኩዘው ምን ድርጊት መወሰድ ይችላሉ?",reflect3:"ስለ ተማሩት ነገር ትንሽ ጊዜ ወስደው ጸልዩ።" },
   dailyDevotional: { title:"ዕለታዊ ጸሎት",subtitle:"ሎሚ ዝሃሸ ቃልን ምሕሳብን",loading:"ናይ ሎሚ ቃል ኣብ ምጽዓን...",verseNotFound:"ቃል ኣይተረኽበን",verseNotFoundDesc:"ቃለ-ኩነታት ምምጻእ ኣይተኻእለን። ደጊምካ ፈትን።",reflectAndPray:"ሕሰቦ ጸልዩ",reflect1:"ናይ ሎሚ ቃሉ ኣብ ህይወትካ ኣብዚ መዓልቲ እዚ እንታይ ይብሎ?",reflect2:"ካብዚ ሓቂ ዘለዎ ምንታይ ስጉምቲ ክትወስድ ትኽእል?",reflect3:"ብዛዕባ ዝተምሃርካዮ ሕጂ ጸሊ።" },
   journal: { title:"ዕለታዊ ማስታወሻ",todaysVerse:"ናይ ሎሚ ቃል",placeholder:"ብዛዕባ ናይ ሎሚ ቃል ናትካ ኣስተንትኖ ጸሓፍ...",chars:"ፊደላት",saved:"ተቐሚጡ!" },
   prayer: { title:"መወቃዕቲ ጸሎት",newRequest:"ሓዲሽ ጸሎት",prayForThis:"ብዛዕባ እዚ ጸልዩ",prayed:"ጸሊኹ",prayerCount:"ሰባት ኣብ ምጽሃ",anonymous:"ስም-ኣልቦ",categories:{health:"ጥዕና",family:"ስድራ",work:"ስራሕ",faith:"እምነት",other:"ካልእ"} },
   settings: { title:"ቅንብር",language:"ቋንቋ",selectLanguage:"ቋንቋ ምረጽ",notifications:"ምልክታ",logout:"ውጻእ",saveSettings:"ቅንብር ኣቐምጥ",settingsSaved:"ቅንብር ተቐሚጡ!" },
   legal: { deletion:{title:"ሕቶ ምስሓብ ውሂብ",submit:"ሕቶ ምስሓብ ኣእቱ",confirm:"እዚ ምዃኑ ርዳእ።",success:"ሕቶ ምስሓብካ ተቐቢሉ ኣብ 30 መዓልቲ ይፍጸም።"},lastUpdated:"ናይ ዝሓለፈ ምሕዳስ" },
   studyRooms: { title:"ክፍልታት ትምህርቲ",subtitle:"ምስ ኣማኒያን ንምምሃር፣ ምርኻብ ናይ ኢምነት ዕቤት።",searchPlaceholder:"ክፍልታት ደሊ",filters:{all:"ኩሉ",myRooms:"ናተይ ክፍልታት",public:"ይፋ",private:"ውልቃዊ"},createButton:"ክፍሊ ፍጠር",join:"ተጸምበር",open:"ክፈት",invite:"ዕደም",emptyTitle:"ናይ ትምህርቲ ክፍልታት የለን",emptyText:"ቀዳማይ ክፍሊ ፍጠር ካልኦትን ዕደም።" },
   createRoom: { title:"ናይ ትምህርቲ ክፍሊ ፍጠር",name:"ስም ክፍሊ",description:"ምግላጽ",language:"ቋንቋ",privacy:"ምስጢርነት",public:"ይፋ",private:"ውልቃዊ",cancel:"ሰርዝ",submit:"ክፍሊ ፍጠር" },
   room: { chatTab:"ዕላል",versesTab:"ቃላት",prayerTab:"ጸሎት",aboutTab:"ብዛዕባ",messagePlaceholder:"መልእኽቲ ጸሓፍ",shareVerse:"ቃል ካፍል",addPrayerRequest:"ሕቶ ጸሎት ወሲኽ",praying:"ኣብ ምጽሃ" },
   errors: { generic:"ዝተሓለፈ ዘሎ ነገር ኣሎ። ደጊምካ ፈትን።",network:"ናይ ኔትወርክ ጌጋ።",aiUnavailable:"ናይ AI ኣገልግሎት ንሕጂ ኣይርከብን።" },
};

const fr = {
   common: { read:"Lire",share:"Partager",save:"Enregistrer",search:"Rechercher",generate:"Générer",tryAgain:"Réessayer",loading:"Chargement...",copy:"Copier",copied:"Copié!",saving:"Enregistrement...",searching:"Recherche en cours...",close:"Fermer",cancel:"Annuler",confirm:"Confirmer",delete:"Supprimer",edit:"Modifier",back:"Retour",next:"Suivant",done:"Terminé",yes:"Oui",no:"Non",submit:"Soumettre",download:"Télécharger",play:"Lire",pause:"Pause",retry:"Réessayer" },
   navigation: { home:"Accueil",daily:"Quotidien",bible:"Bible",prayer:"Prière",community:"Communauté",settings:"Paramètres",login:"Connexion",logout:"Déconnexion" },
   home: { greetingMorning:"Bonjour",greetingEvening:"Bonsoir",greetingAfternoon:"Bon après-midi",subtitle:"Grandissez dans la foi aujourd'hui",verseOfDay:"Verset du Jour",todaysScripture:"Écriture d'aujourd'hui",aiInsight:"Perspective Spirituelle IA",generateInsight:"Générer une Perspective",generatingInsight:"Génération en cours...",dailyJournal:"Journal Quotidien",startWriting:"Commencer à écrire",reflectionPrompt:"Que signifie pour vous le verset d'aujourd'hui?",dailyReflection:"Réflexion Quotidienne",readMore:"Lire la suite",aiReflection:"Réflexion IA du Jour",generateReflection:"Générer une Réflexion",generatingReflection:"Génération de votre réflexion...",studyPlansDesc:"Continuez votre parcours biblique guidé",noVerses:"Aucun verset disponible",tryAgain:"Veuillez réessayer" },
   support: { title:"Assistance FaithLight",subtitle:"Assistant IA",greeting:"Bonjour! 👋 Je suis l'assistant d'assistance FaithLight.",intro:"Comment puis-je vous aider aujourd'hui? Vous pouvez choisir un problème courant ci-dessous ou poser votre propre question.",language:"Langue",placeholder:"Décrivez votre problème...",cantResolve:"Impossible de résoudre?",emailUs:"Email",issue:{pageNotLoading:"Page ne charge pas",languageNotChanging:"La langue ne change pas",aiResponseFailed:"Réponse IA échouée",quizNotWorking:"Le quiz ne fonctionne pas",audioBibleProblem:"Problème avec la Bible audio",verseSharingProblem:"Problème de partage de verset",somethingElse:"Autre chose"} },
   dailyDevotional: { title:"Dévotion Quotidienne",subtitle:"Un verset et une réflexion pour inspirer votre journée",loading:"Chargement du verset du jour...",verseNotFound:"Verset introuvable",verseNotFoundDesc:"Impossible de charger le verset biblique. Veuillez réessayer plus tard.",reflectAndPray:"Réfléchir et Prier",reflect1:"Comment ce verset parle-t-il à votre vie aujourd'hui?",reflect2:"Quelle action pouvez-vous prendre sur la base de cette vérité?",reflect3:"Prenez un moment pour prier sur ce que vous avez appris." },
   journal: { title:"Journal Quotidien",todaysVerse:"Verset du Jour",placeholder:"Écrivez votre réflexion sur le verset d'aujourd'hui...",chars:"caractères",saved:"Enregistré!" },
   studyRooms: { title:"Salles d'Étude",subtitle:"Rejoignez les croyants pour étudier, discuter et grandir ensemble.",searchPlaceholder:"Rechercher des salles",filters:{all:"Tous",myRooms:"Mes Salles",public:"Public",private:"Privé"},createButton:"Créer une Salle",join:"Rejoindre",open:"Ouvrir",invite:"Inviter",emptyTitle:"Aucune salle d'étude pour le moment",emptyText:"Créez la première salle et invitez d'autres à étudier ensemble." },
   createRoom: { title:"Créer une Salle d'Étude",name:"Nom de la Salle",description:"Description",language:"Langue",category:"Catégorie",privacy:"Confidentialité",public:"Public",private:"Privé",inviteCode:"Code d'Invitation",maxMembers:"Nombre Maximum de Membres",allowPrayerRequests:"Autoriser les Demandes de Prière",allowVerseSharing:"Autoriser le Partage de Versets",allowAISummaries:"Autoriser les Résumés IA",cancel:"Annuler",submit:"Créer une Salle" },
   room: { chatTab:"Discussion",versesTab:"Versets",prayerTab:"Prière",aboutTab:"À Propos",messagePlaceholder:"Écrivez un message",shareVerse:"Partager un Verset",addPrayerRequest:"Ajouter une Demande de Prière",praying:"Prie" },
   errors: { generic:"Quelque chose s'est mal passé. Veuillez réessayer.",network:"Erreur réseau.",aiUnavailable:"Le service IA est temporairement indisponible." },
};

export const LOCALES = { en, om, am, ar, sw, fr, ti };

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English',      nativeName: 'English' },
  { code: 'om', name: 'Afaan Oromoo', nativeName: 'Afaan Oromoo' },
  { code: 'am', name: 'Amharic',      nativeName: 'አማርኛ' },
  { code: 'ar', name: 'Arabic',       nativeName: 'العربية' },
  { code: 'sw', name: 'Swahili',      nativeName: 'Kiswahili' },
  { code: 'fr', name: 'French',       nativeName: 'Français' },
  { code: 'ti', name: 'Tigrinya',     nativeName: 'ትግርኛ' },
];

/**
 * Flatten a nested locale object to dot-notation keys.
 * { home: { verseOfDay: "…" } } → { "home.verseOfDay": "…" }
 */
export function flattenLocale(langCode) {
  const locale = LOCALES[langCode] || LOCALES.en;
  const result = {};
  function walk(obj, prefix) {
    for (const key of Object.keys(obj)) {
      const path = prefix ? `${prefix}.${key}` : key;
      if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
        walk(obj[key], path);
      } else {
        result[path] = obj[key];
      }
    }
  }
  walk(locale, '');
  return result;
}

export function getLocale(langCode) {
  return LOCALES[langCode] || LOCALES.en;
}