export const holidayContent = {
  'ash-wednesday': {
    title: {
      en: 'Ash Wednesday',
      fr: 'Mercredi des Cendres',
      sw: 'Jumatano ya Majivu',
      ar: 'أربعاء الرماد',
      ti: 'ረቡዕ ሓመድ',
      om: 'Roobii Awwaaraa',
    },
    description: {
      en: 'Begins Lent, a season of repentance and reflection.',
      fr: 'Marque le début du Carême, période de repentance.',
      sw: 'Huanzisha Kwaresima, kipindi cha toba na tafakari.',
      ar: 'يبدأ الصوم الكبير، زمن التوبة والتأمل.',
      ti: 'መጀመርታ ጾም፣ ጊዜ ንስሓን ንግምትን።',
      om: 'Qophii soomaa jalqaba, yeroo tobaa fi yaada.',
    },
  },
  'palm-sunday': {
    title: {
      en: 'Palm Sunday',
      fr: 'Dimanche des Rameaux',
      sw: 'Jumapili ya Matawi',
      ar: 'أحد الشعانين',
      ti: 'ሰንበት ዕንባባ',
      om: 'Dilbata Muka',
    },
    description: {
      en: "Marks Jesus' triumphal entry into Jerusalem.",
      fr: "Marque l'entrée triomphale de Jésus à Jérusalem.",
      sw: 'Inaadhimisha kuingia kwa Yesu Yerusalemu kwa ushindi.',
      ar: 'يُحيي دخول يسوع إلى أورشليم منتصرًا.',
      ti: 'መእተዊ ድልዊ ናይ ክርስቶስ ናብ ኢየሩሳሌም።',
      om: 'Seensa injifannoo Yesuus gara Yerusaalem ni yaadata.',
    },
  },
  'maundy-thursday': {
    title: {
      en: 'Maundy Thursday',
      fr: 'Jeudi Saint',
      sw: 'Alhamisi Kuu',
      ar: 'خميس العهد',
      ti: 'ሓሙስ ቅዱስ',
      om: 'Kamisa Qulqulluu',
    },
    description: {
      en: 'Remembers the Last Supper of Jesus with His disciples.',
      fr: 'Commémore le dernier repas de Jésus avec ses disciples.',
      sw: 'Inaadhimisha Karamu ya Mwisho ya Yesu pamoja na wanafunzi wake.',
      ar: 'يحيي ذكرى العشاء الأخير ليسوع مع تلاميذه.',
      ti: 'ምስ ደቂ መዛሙርቱ ዝበልዖ ዳሕረዋይ ድራር ይዝክር።',
      om: 'Irbaata dhumaa Yesuus bartoota isaa wajjin nyaate ni yaadata.',
    },
  },
  'good-friday': {
    title: {
      en: 'Good Friday',
      fr: 'Vendredi Saint',
      sw: 'Ijumaa Kuu',
      ar: 'الجمعة العظيمة',
      ti: 'ዓርቢ ቅዱስ',
      om: 'Jimaata Guddaa',
    },
    description: {
      en: 'Commemorates the crucifixion and sacrifice of Jesus Christ.',
      fr: 'Commémore la crucifixion et le sacrifice de Jésus-Christ.',
      sw: 'Inaadhimisha kusulubiwa na dhabihu ya Yesu Kristo.',
      ar: 'يحيي ذكرى صلب يسوع المسيح وتضحيته.',
      ti: 'ስቅለትን መስዋእትን ክርስቶስ ይዝክር።',
      om: 'Fannoo fi aarsaa Yesuus Kiristoos ni yaadata.',
    },
  },
  'holy-saturday': {
    title: {
      en: 'Holy Saturday',
      fr: 'Samedi Saint',
      sw: 'Jumamosi Takatifu',
      ar: 'السبت المقدس',
      ti: 'ቀዳም ቅዱስ',
      om: 'Sanbata Qulqulluu',
    },
    description: {
      en: 'A day of waiting, silence, and hope before Easter.',
      fr: 'Jour d\'attente, de silence et d\'espérance avant Pâques.',
      sw: 'Siku ya kusubiri, ukimya, na tumaini kabla ya Pasaka.',
      ar: 'يوم انتظار وصمت ورجاء قبل القيامة.',
      ti: 'ቅድሚ ፋሲካ መዓልቲ ጽባሕን ጸጥታን ተስፋን።',
      om: 'Guyyaa eegumsaa, callisummaa fi abdii Faasikaa dura.',
    },
  },
  'easter-sunday': {
    title: {
      en: 'Easter Sunday',
      fr: 'Dimanche de Pâques',
      sw: 'Jumapili ya Pasaka',
      ar: 'عيد القيامة',
      ti: 'ሰንበት ፋሲካ',
      om: 'Dilbata Faasikaa',
    },
    description: {
      en: 'Celebrates the resurrection of Jesus Christ, the foundation of Christian faith.',
      fr: 'Célèbre la résurrection de Jésus-Christ, fondement de la foi chrétienne.',
      sw: 'Inaadhimisha ufufuo wa Yesu Kristo, msingi wa imani ya Kikristo.',
      ar: 'يحتفل بقيامة يسوع المسيح، أساس الإيمان المسيحي.',
      ti: 'ትንሳኤ ክርስቶስ ይኽብር፣ መሰረት እምነት ክርስትና።',
      om: 'Du\'aa ka\'uu Yesuus Kiristoos ni kabaja, bu\'uura amantii Kiristaanaa.',
    },
  },
  'easter-monday': {
    title: {
      en: 'Easter Monday',
      fr: 'Lundi de Pâques',
      sw: 'Jumatatu ya Pasaka',
      ar: 'اثنين الفصح',
      ti: 'ሰኑይ ፋሲካ',
      om: 'Wiixata Faasikaa',
    },
    description: {
      en: 'Continues the celebration of Christ\'s resurrection.',
      fr: 'Poursuit la célébration de la résurrection du Christ.',
      sw: 'Inaendelea na sherehe ya ufufuo wa Kristo.',
      ar: 'يواصل الاحتفال بقيامة المسيح.',
      ti: 'በዓል ትንሳኤ ክርስቶስ ይቕጽል።',
      om: 'Kabaja du\'aa ka\'uu Kiristoos itti fufa.',
    },
  },
  'ascension-day': {
    title: {
      en: 'Ascension Day',
      fr: 'Ascension',
      sw: 'Siku ya Kupaa',
      ar: 'عيد الصعود',
      ti: 'ዕርገት',
      om: 'Guyyaa Ol-baasaa',
    },
    description: {
      en: 'Commemorates Jesus ascending into heaven.',
      fr: 'Commémore l\'ascension de Jésus au ciel.',
      sw: 'Inaadhimisha Yesu kupaa mbinguni.',
      ar: 'يُحيي صعود يسوع إلى السماء.',
      ti: 'ዕርገት ክርስቶስ ናብ ሰማይ።',
      om: 'Yesuus samii ol ba\'uu isaa ni yaadata.',
    },
  },
  pentecost: {
    title: {
      en: 'Pentecost',
      fr: 'Pentecôte',
      sw: 'Pentekoste',
      ar: 'عيد العنصرة',
      ti: 'ጰንጠቆስጤ',
      om: 'Phenteqostee',
    },
    description: {
      en: 'Celebrates the coming of the Holy Spirit.',
      fr: 'Célèbre la venue du Saint-Esprit.',
      sw: 'Inaadhimisha kuja kwa Roho Mtakatifu.',
      ar: 'يحتفل بنزول الروح القدس.',
      ti: 'መጻኢ መንፈስ ቅዱስ ይኽብር።',
      om: 'Dhufaatii Hafuura Qulqulluu ni kabaja.',
    },
  },
  'trinity-sunday': {
    title: {
      en: 'Trinity Sunday',
      fr: 'Dimanche de la Trinité',
      sw: 'Jumapili ya Utatu',
      ar: 'أحد الثالوث',
      ti: 'ሰንበት ስላሴ',
      om: 'Dilbata Sillaasee',
    },
    description: {
      en: 'Honors God as Father, Son, and Holy Spirit.',
      fr: 'Honore Dieu comme Père, Fils et Saint-Esprit.',
      sw: 'Humheshimu Mungu kama Baba, Mwana, na Roho Mtakatifu.',
      ar: 'يكرم الله الآب والابن والروح القدس.',
      ti: 'ኣምላኽ ከም ኣቦን ወድን መንፈስ ቅዱስን ይኽብር።',
      om: 'Waaqa akka Abbaa, Ilmaa fi Hafuura Qulqulluu ni kabaja.',
    },
  },
  christmas: {
    title: {
      en: 'Christmas',
      fr: 'Noël',
      sw: 'Krismasi',
      ar: 'عيد الميلاد',
      ti: 'ልደት',
      om: 'Ayyaana Dhalootaa',
    },
    description: {
      en: 'Celebrates the birth of Jesus Christ, the Savior of the world.',
      fr: 'Célèbre la naissance de Jésus-Christ, le Sauveur du monde.',
      sw: 'Inaadhimisha kuzaliwa kwa Yesu Kristo, Mwokozi wa ulimwengu.',
      ar: 'يحتفل بميلاد يسوع المسيح، مخلص العالم.',
      ti: 'ልደት ክርስቶስ ይኽብር፣ መድኃኒ ዓለም።',
      om: 'Dhaloota Yesuus Kiristoos, Fayyisaa addunyaa ni kabaja.',
    },
  },
  epiphany: {
    title: {
      en: 'Epiphany',
      fr: 'Épiphanie',
      sw: 'Epifania',
      ar: 'عيد الغطاس',
      ti: 'ጥምቀት',
      om: 'Mul\'ifannaa',
    },
    description: {
      en: 'Celebrates the revelation of Christ to the nations.',
      fr: 'Célèbre la révélation du Christ aux nations.',
      sw: 'Inaadhimisha kufunuliwa kwa Kristo kwa mataifa.',
      ar: 'يحتفل بإعلان المسيح للأمم.',
      ti: 'መግለጺ ክርስቶስ ንኣህዛብ ይዝክር።',
      om: 'Mul\'achuu Kiristoos sabootaaf ni kabaja.',
    },
  },
  'all-saints-day': {
    title: {
      en: 'All Saints\' Day',
      fr: 'Toussaint',
      sw: 'Sikukuu ya Watakatifu Wote',
      ar: 'عيد جميع القديسين',
      ti: 'በዓል ኩሎም ቅዱሳን',
      om: 'Guyyaa Qulqulloota Hunda',
    },
    description: {
      en: 'Honors all saints and faithful believers who have gone before us.',
      fr: 'Honore tous les saints et les fidèles croyants qui nous ont précédés.',
      sw: 'Huwaheshimu watakatifu wote na waamini waaminifu waliotutangulia.',
      ar: 'يكرم جميع القديسين والمؤمنين الأمناء الذين سبقونا.',
      ti: 'ንኹሎም ቅዱሳንን እሙናት ኣመንትን ይኽብር።',
      om: 'Qulqulloota hundaa fi amanamtoota nu dura darban ni kabaja.',
    },
  },
};