// Curated daily verse list — 60 verses that cycle by date
// Same verse for all users on the same calendar day (date-seeded, no API needed)
// Each entry has English (en) and Afaan Oromoo (om) if available

export const DAILY_VERSES = [
  { ref: 'Jeremiah 29:11', omRef: 'Ermiyaas 29:11',     en: 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.',                     om: 'Nanin beeka yaada isin irratti qabaadhaa jedha Waaqayyo, yaadi nageenya keessan, hamaa keessaniin miti, inni gara boriif abdii isinii kennuuf.' },
  { ref: 'John 3:16', omRef: 'Yohaannis 3:16',          en: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.',                         om: 'Waaqayyo addunyaa kana jaalateef ilma isaa tokkicha kennee, nama isaatti amanu hunduu baduu dhiisee jireenya bara baraa qabaatu.' },
  { ref: 'Psalm 23:1', omRef: 'Faarfannaa 23:1',         en: 'The LORD is my shepherd, I lack nothing.',                                                                                                                   om: 'Waaqayyo tiksee koo dha; waan tokkolle ana hin dhibu.' },
  { ref: 'Romans 8:28', omRef: 'Roomaa 8:28',        en: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.',                                 om: 'Warra Waaqayyoon jaallatan, warra yaada isaarratti waamaman hundaaf, waan hundumaa waan gaariif hojjeta.' },
  { ref: 'Philippians 4:13', omRef: 'Filiphisiyuus 4:13',   en: 'I can do all this through him who gives me strength.',                                                                                                       om: 'Kan na jabeessuun waan hundumaa gochuu danda\'a.' },
  { ref: 'Isaiah 41:10', omRef: 'Isaayaas 41:10',       en: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you.',                                              om: 'Sodaachuu dhiisi, an siwaliin jira; haltuu hin hin galin, an Waaqayyo kee; nan si jabeessa, nan si gargaara.' },
  { ref: 'Proverbs 3:5-6', omRef: 'Fakkeenya 3:5-6',     en: 'Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.',        om: 'Waaqayyootti garaa kee guutuun amani, hubannoo keetii hin hirkatin; karaa kee hunda keessatti isa beeki, innis daandii kee ni qajeelesssa.' },
  { ref: 'Matthew 11:28', omRef: 'Maatewos 11:28',      en: 'Come to me, all you who are weary and burdened, and I will give you rest.',                                                                                  om: 'Natti koolaa, kan hiraarsitaniif kan ulfaataan isinitti baate hundi, annis boqonnaa isinii kenna.' },
  { ref: 'Psalm 46:1', omRef: 'Faarfannaa 46:1',         en: 'God is our refuge and strength, an ever-present help in trouble.',                                                                                           om: 'Waaqayyo mana baqannaa keenya fi jabeenya keenya, gargaarsa yeroo rakkoo argamuu dha.' },
  { ref: 'Romans 8:38-39',     en: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers can separate us from the love of God.', om: 'Waan tokkollee jaalala Waaqayyo kan Yesus Kiristoos Gooftaa keenya keessatti argamu irraa nu addaan hin baatu.' },
  { ref: 'Psalm 119:105', omRef: 'Faarfannaa 119:105',      en: 'Your word is a lamp for my feet, a light on my path.',                                                                                                       om: 'Dubbiin kee ifaa miila kootii fi ifaa karaa kootii dha.' },
  { ref: 'Joshua 1:9', omRef: 'Iyyaasuu 1:9',         en: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.',                                 om: 'Jabaadhu, obsaa; hin sodaatin, hin qaayin; Waaqayyo Waaqaa kee iddoo deemtu hunda siwaliin jira.' },
  { ref: '2 Timothy 1:7',      en: 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.',                                                           om: 'Waaqayyo hafuura sodaa nutti hin kenninne, garuu hafuura humna, jaalalaa fi of to\'annoo nutti kenne.' },
  { ref: 'Matthew 6:33', omRef: 'Maatewos 6:33',       en: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.',                                                       om: 'Garuu mootummaa Waaqayyoo fi haqummaa isaa dursa barbaadaa, waan kana hundi isiniif dabalamee kennama.' },
  { ref: 'Lamentations 3:22-23', en: 'Because of the LORD\'s great love we are not consumed, for his compassions never fail. They are new every morning.',                                     om: 'Jaalala Waaqayyootiin hin badine, araara isaa hin dhumne; guyyaa haaraa kalee guyyaa hundumaa haarofata.' },
  { ref: 'Psalm 34:18', omRef: 'Faarfannaa 34:18',        en: 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.',                                                                          om: 'Waaqayyo gara kan garaan isaa cabee ni dhiyaata, kan hafuurri isaa cabe ni oolcha.' },
  { ref: 'Isaiah 40:31', omRef: 'Isaayaas 40:31',       en: 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles.',                                                             om: 'Warra Waaqayyootti abdatan humna haaraa argatu, akka arboorra ni baanu.' },
  { ref: 'Philippians 4:6-7',  en: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.',                        om: 'Waan tokkolle hin yaaddeeffatiin, garuu kadhannaan waan barbaaddan Waaqayyoof himaa.' },
  { ref: 'John 14:6', omRef: 'Yohaannis 14:6',          en: 'Jesus answered, "I am the way and the truth and the life. No one comes to the Father except through me."',                                                  om: 'Yesuus, "Antu karaa fi dhugaa fi jireenya dha; namni tokkollee Abbaa bira ana malee hin dhufu" jedhe.' },
  { ref: 'Psalm 27:1',         en: 'The LORD is my light and my salvation — whom shall I fear? The LORD is the stronghold of my life — of whom shall I be afraid?',                             om: 'Waaqayyo ifaa fi fayyisaa koo dha; eenyu nan sodaata? Waaqayyo jaagaa jireenya koo dha; eenyu naan rifata?' },
  { ref: 'Romans 5:8', omRef: 'Roomaa 5:8',         en: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.',                                                         om: 'Garuu Waaqayyo jaalala isaa nuuf kana agarsiise: yeroo hanga ammaatti cubbamoota taanetti Kiristoosiin nuu du\'e.' },
  { ref: '1 Corinthians 13:13', omRef: '1 Qorontos 13:13', en: 'And now these three remain: faith, hope and love. But the greatest of these is love.',                                                                       om: 'Amma amantaa, abdii fi jaalalli sadanuu ni hafan, garuu caalaan isaanii jaalala dha.' },
  { ref: 'Psalm 91:1',         en: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.',                                                                    om: 'Kan bakka dhokannaa Waaqa ol ta\'e keessa jiraatu ibsaa Kan Hunda Danda\'uu jalatti ni boqota.' },
  { ref: 'Ephesians 2:8-9',    en: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works.',                           om: 'Amantaadhaan araarama argattaniiru, kun isarraa miti, kennaatu Waaqayyoo ti, hojii irraas miti.' },
  { ref: 'John 10:10',         en: 'I have come that they may have life, and have it to the full.',                                                                                               om: 'Ani jireenya qabaataniif, jireenya guutuu qabaataniif dhufe.' },
  { ref: 'Galatians 5:22-23',  en: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.',                              om: 'Atiidhaa hafuura jaatala, gammachuu, nageenyaa, obsa, toltuu, gaariummaa, amantaa, gadi-buusa fi of to\'annoo dha.' },
  { ref: 'Hebrews 11:1', omRef: 'Ibroota 11:1',       en: 'Now faith is confidence in what we hope for and assurance about what we do not see.',                                                                        om: 'Amantaan waan abdannu irkoo fi waan hin mul\'annee ragaa dha.' },
  { ref: 'Matthew 5:16',       en: 'Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.',                                                   om: 'Ifni keessan dura namootaa akka ifa godhu, isaaniis hojii garii keessan argan, Abbaa keessan kan samiitti akka galateeffatan.' },
  { ref: 'Romans 12:2',        en: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.',                                                              om: 'Addunyaa kanaan hin fakkaatinaa, garuu sammuu haaromsuu dhaan geeddaramaa.' },
  { ref: '2 Corinthians 5:17', en: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!',                                                          om: 'Kanaafuu namni Kiristoos keessa jiru uumama haaraa dha; kan durii darbe, haaraan nu dhufee jira.' },
  { ref: 'Psalm 37:4',         en: 'Take delight in the LORD, and he will give you the desires of your heart.',                                                                                  om: 'Waaqayyoon boonaa, innis fedhii garaa kee siif guuta.' },
  { ref: 'Mark 11:24',         en: 'Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.',                                             om: 'Kanaafuu nan isinitti hima, waan kadhatan hundumaa argatanii jirtan amantaa qabaannaan, isiniif ta\'a.' },
  { ref: 'Colossians 3:23',    en: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.',                                                           om: 'Waan hojjetan hundumaa akka nama biroof osoo hin taane akka Gooftaaf hojjetan garaa guutuun hojjechaa.' },
  { ref: '1 Peter 5:7',        en: 'Cast all your anxiety on him because he cares for you.',                                                                                                     om: 'Yaaddoo keessan hunda isatti gataa, inni isin ni yaada waan ta\'eef.' },
  { ref: 'Nahum 1:7',          en: 'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.',                                                                       om: 'Waaqayyo gaarii dha, citaan rakkoo keessatti; warra isaatti amanan ni beeka.' },
  { ref: 'Micah 6:8',          en: 'He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.',       om: 'Namaa, waan gaarii sitti agarsiisee jira; Waaqayyo waan sirraa barbaadu maali? Haqaan hojjechuu, araara jaalachuu fi gad-deebinaan Waaqayyoo keetiin deemuu.' },
  { ref: 'Psalm 55:22',        en: 'Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.',                                                            om: 'Rakkoo kee Waaqayyotti darbadhu, inni si gargaara; haqaawaa hanga yeroo hundumaa hin afoofsisu.' },
  { ref: 'James 1:17', omRef: 'Yaaqoob 1:17',  en: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights.',                                         om: 'Kennaan gaariin hundinuu, kennaan mudaa hin qabnes hundinuu, gubbaadhaa irraa ni dhufa; innis Abbaa ifootaa biraa dhufa.' },
  { ref: 'John 15:5',          en: 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.',                        om: 'Antu ajaa; isin cilee dha. Kan ana keessa jiruu ana keessas jiraate ba\'aa baay\'ee fixxata; ana malee waan tokkollee hojjechuun hindanda\'amu.' },
  { ref: 'Psalm 103:12',       en: 'As far as the east is from the west, so far has he removed our transgressions from us.',                                                                     om: 'Baha dhihaa irraa fagaatetti, faallaa keenya nu irraa fageessera.' },
  { ref: 'Proverbs 31:25',     en: 'She is clothed with strength and dignity; she can laugh at the days to come.',                                                                               om: 'Uffanni isii jabeenya fi ulfinaa dha; guyyaa dhufuuf ni kolfiti.' },
  { ref: 'Luke 6:38',          en: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.',                          om: 'Kennaa, isinifis kennamaaf; safarama gaariitu sararaa olitti guutuudhaan garaa keessan keessa naqama.' },
  { ref: '3 John 1:2',         en: 'Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well.',                             om: 'Jaalli koo, akkuma lubbuun kee badhaatuttuu waan hundumaa keessatti ni badhaata, fayyas akka qabaattu kadhanna.' },
  { ref: 'Psalm 1:3',          en: 'That person is like a tree planted by streams of water, which yields its fruit in season and whose leaf does not wither.',                                   om: 'Inni akka muka laga cinaa facaafamee yero isaa keessatti fuduraa argu, harroonnis isaa hin gube.' },
  { ref: 'Matthew 7:7',        en: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.',                                                         om: 'Kadhaa, isinii kennamaaf; barbaadaa, ni argattu; dhaabaa, isinii banama.' },
  { ref: 'Revelation 21:4', omRef: 'Mul\'ata 21:4',    en: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.',          om: 'Harqoota isaanii irraa ni haqata; du\'aas, gadoo, iyaas, dhukkubaas hin jiraatu, waan duri darbee jira.' },
  { ref: 'Psalm 139:14',       en: 'I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.',                                                 om: 'Nan si galateeffadha, waan naaf raajessitef; hojiin kee gaarummaan guutaa dha, kana hundi naaf beekama.' },
  { ref: 'Deuteronomy 31:8',   en: 'The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged.',                  om: 'Waaqayyo dura kee deema, siwaliin jira; si hin dhaqu, si hin dhiisu; hin sodaatin, hin gaddiin.' },
  { ref: 'Ephesians 3:20',     en: 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.',                              om: 'Kan humnaa isaa nu keessatti hojjatuun waan hunda kadhannu yookiin yaannu caalaa hojjechuuf danda\'uuf.' },
  { ref: 'Psalm 16:11',        en: 'You make known to me the path of life; you will fill me with joy in your presence, with eternal pleasures at your right hand.',                              om: 'Karaa jireenya naaf agarsiista; gammachuu guutuu fuula keetiin, biyyoon bara baraa harki mirgaa keetii.' },
  { ref: '2 Chronicles 7:14',  en: 'If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven.',  om: 'Yoo uummanni koo maqaa kootiin waamaman gad-of-qabatanii, kadhatanii, fuula koo barbaaduudhaanuu daandii hamaa isaanii irraa deebi\'an.' },
  { ref: 'Psalm 121:1-2',      en: 'I lift up my eyes to the mountains — where does my help come from? My help comes from the LORD, the Maker of heaven and earth.',                            om: 'Gara geengoo ilaalee gola koo eessa irraa dhufa? Gola koo irra Waaqayyoo samii fi lafaa uume irraa dhufa.' },
  { ref: 'John 8:12',          en: 'When Jesus spoke again to the people, he said, "I am the light of the world. Whoever follows me will never walk in darkness."',                             om: 'Yesuus uummata dubbii deebisee akkanaan dhaadde: "Antu ifaa addunyaa ti; kan na hordofu gara dukkana hin deemu."' },
  { ref: 'Numbers 6:24-26',    en: 'The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you; the LORD turn his face toward you and give you peace.',        om: 'Waaqayyo siin haa eebbe, siin haa tiksu; Waaqayyo fuula isaa itti si haa fakkeesu, sitti haa araaramuu; nageenyas sii haa kenne.' },
  { ref: 'Psalm 145:18',       en: 'The LORD is near to all who call on him, to all who call on him in truth.',                                                                                  om: 'Waaqayyo dhugaadhaan warra isa waaman hundaaf dhiyoo dha.' },
  { ref: 'Romans 15:13',       en: 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.',              om: 'Waaqayyo abdii ta\'ee gammachuu fi nageenyaa guutuun isin haa guutu, amantaadhaan inni abdii hafuurri qulqulluudhaan gara ol-bahiinsaatti isinii haa baasu.' },
  { ref: 'Zephaniah 3:17',     en: 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you.',                om: 'Waaqayyo Waaqaa kee siwaliin jira; jabaadha inni fayyisaa; isiniin kan boonuu dha, jaalala isaa keessatti sirratti gammada.' },
  { ref: 'Psalm 46:10',        en: 'He says, "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth."',                                        om: '"Callisuudhaan na Waaqayyo ta\'uu koo beekaa; goyyoomessa dha uummata keessatti, goyyoomessa dha lafaa keessatti."' },
  { ref: 'Habakkuk 3:19',      en: 'The Sovereign LORD is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights.',                                      om: 'Waaqayyo Gooftaan jabeenya koo ti; miila koo akka miila re\'ee na godha, bakka ol-ta\'aa irra na godha.' },
  { ref: 'Matthew 28:20',      en: '"And surely I am with you always, to the very end of the age."',                                                                                            om: '"Guyyaa guyyaa hanga raawwi addunyaatti siwaliin jira."' },
];

/**
 * Get today's verse — stable for all users on same calendar day.
 * Uses a seed from full date string (YYYY-MM-DD) so it changes at midnight.
 */
export function getDailyVerse(langCode = 'en') {
  const today = new Date();
  const dateStr = `${today.getFullYear()}-${today.getMonth()}-${today.getDate()}`;
  // Simple hash of date string → stable index
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    hash = (hash * 31 + dateStr.charCodeAt(i)) & 0xffffffff;
  }
  const idx = Math.abs(hash) % DAILY_VERSES.length;
  const entry = DAILY_VERSES[idx];

  // Use localized book reference when available
  const localizedRef = (langCode === 'om' && entry.omRef) ? entry.omRef : entry.ref;

  return {
    ref: localizedRef,
    refEn: entry.ref,
    text: (langCode === 'om' && entry.om) ? entry.om : entry.en,
    textEn: entry.en,
    textOm: entry.om || null,
    hasOromoo: !!entry.om,
    // Rule: Bible text comes from verified dataset (om field), never auto-translated
    isVerifiedTranslation: langCode === 'om' ? !!entry.om : true,
  };
}