import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { FileText, Loader2, Download } from 'lucide-react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';

export default function SermonStudyGuide({ outline, theme }) {
  const [loading, setLoading] = useState(false);
  const [guide, setGuide] = useState(null);

  const generateGuide = async () => {
    if (!outline) return;
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Create a church member study guide for this sermon:
Title: "${outline.title || theme}"
Big Idea: "${outline.big_idea || ''}"
Sections: ${(outline.outline_sections || []).map(s => `${s.title || s.heading}: ${(s.key_points || s.points || []).join(', ')}`).join('\n')}
Application: "${outline.application || ''}"

Generate a study guide with:
1. A 3-sentence sermon summary for church members
2. 5 reflection questions (mix of personal and discussion-based)
3. 3 "this week" practical application steps
4. 2 deeper scripture study suggestions

Return JSON: {"summary":"...","reflection_questions":["...x5"],"weekly_steps":["...x3"],"deeper_study":["...x2"]}`,
        response_json_schema: {
          type: 'object',
          properties: {
            summary: { type: 'string' },
            reflection_questions: { type: 'array', items: { type: 'string' } },
            weekly_steps: { type: 'array', items: { type: 'string' } },
            deeper_study: { type: 'array', items: { type: 'string' } },
          }
        }
      });
      setGuide(result);
    } catch {
      toast.error('Could not generate study guide');
    }
    setLoading(false);
  };

  const downloadPDF = () => {
    if (!guide || !outline) return;
    const doc = new jsPDF();
    const W = doc.internal.pageSize.getWidth();
    let y = 20;

    const line = (text, size = 11, style = 'normal', color = [30, 30, 30]) => {
      doc.setFontSize(size);
      doc.setFont('helvetica', style);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, W - 30);
      lines.forEach(l => {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(l, 15, y);
        y += size * 0.55;
      });
      y += 2;
    };

    const divider = () => {
      doc.setDrawColor(200, 200, 200);
      doc.line(15, y, W - 15, y);
      y += 5;
    };

    // Header
    doc.setFillColor(49, 46, 129);
    doc.rect(0, 0, W, 35, 'F');
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(outline.title || theme || 'Sermon Study Guide', 15, 18);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Church Member Study Guide  •  FaithLight', 15, 28);
    y = 45;

    // Summary
    line('SERMON SUMMARY', 12, 'bold', [49, 46, 129]);
    divider();
    line(guide.summary, 11);
    y += 4;

    // Reflection questions
    line('REFLECTION QUESTIONS', 12, 'bold', [49, 46, 129]);
    divider();
    (guide.reflection_questions || []).forEach((q, i) => {
      line(`${i + 1}. ${q}`, 10.5);
      y += 3;
    });
    y += 4;

    // Weekly steps
    line('THIS WEEK', 12, 'bold', [49, 46, 129]);
    divider();
    (guide.weekly_steps || []).forEach((s, i) => {
      line(`✓  ${s}`, 10.5);
    });
    y += 4;

    // Deeper study
    line('DEEPER STUDY', 12, 'bold', [49, 46, 129]);
    divider();
    (guide.deeper_study || []).forEach(s => line(`📖 ${s}`, 10.5));

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by FaithLight  •  faithlight.app', 15, 288);

    doc.save(`${(outline.title || theme || 'sermon').slice(0, 40).replace(/\s+/g, '_')}_study_guide.pdf`);
    toast.success('Study Guide PDF downloaded!');
  };

  return (
    <div className="mt-4">
      {!guide ? (
        <button onClick={generateGuide} disabled={loading || !outline}
          className="flex items-center gap-2 text-sm font-bold px-4 py-2.5 rounded-xl bg-green-50 text-green-700 border border-green-200 hover:bg-green-100 transition-all disabled:opacity-50">
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
          {loading ? 'Generating Study Guide…' : 'Generate Study Guide PDF'}
        </button>
      ) : (
        <div className="bg-green-50 border border-green-200 rounded-2xl p-4">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-extrabold text-green-900 flex items-center gap-1.5">
              <FileText className="w-4 h-4" /> Study Guide Ready
            </h4>
            <button onClick={downloadPDF}
              className="flex items-center gap-1.5 text-xs font-bold px-3 py-1.5 bg-green-700 text-white rounded-xl hover:bg-green-800 transition-colors">
              <Download className="w-3.5 h-3.5" /> Download PDF
            </button>
          </div>
          <p className="text-green-800 text-xs leading-relaxed mb-2">{guide.summary}</p>
          <p className="text-green-600 text-xs">{(guide.reflection_questions || []).length} reflection questions • {(guide.weekly_steps || []).length} weekly steps</p>
        </div>
      )}
    </div>
  );
}