import React, { useState } from 'react';
import { FileText, Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function SermonPDFExporter({ sermon }) {
  const [loading, setLoading] = useState(false);

  const generatePDF = async () => {
    if (!sermon) return;
    setLoading(true);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - 2 * margin;
      let yPos = margin;

      // Helper to add text with wrapping
      const addWrappedText = (text, fontSize, isBold = false, isHeading = false) => {
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', isBold ? 'bold' : 'normal');
        const lines = doc.splitTextToSize(text, contentWidth);
        
        lines.forEach((line) => {
          if (yPos + 5 > pageHeight - margin) {
            doc.addPage();
            yPos = margin;
          }
          doc.text(line, margin, yPos);
          yPos += isHeading ? 8 : 6;
        });
      };

      const addSpacer = (height = 5) => {
        yPos += height;
      };

      // Header
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('FaithLight', margin, yPos);
      yPos += 10;

      // Divider
      doc.setDrawColor(100);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 5;

      // Title
      addWrappedText(sermon.title || 'Untitled Sermon', 20, true, true);
      addSpacer(3);

      // Metadata
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const date = new Date().toLocaleDateString();
      const metadata = [
        `Language: ${sermon.language || 'English'}`,
        `Style: ${sermon.style || 'Teaching'}`,
        `Date: ${date}`,
      ];
      metadata.forEach((meta) => {
        addWrappedText(meta, 10);
      });

      addSpacer(8);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 8;

      // Theme
      if (sermon.theme) {
        addWrappedText('THEME', 14, true, true);
        addWrappedText(sermon.theme, 11);
        addSpacer(6);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Main Scripture
      if (sermon.scripture) {
        addWrappedText('MAIN SCRIPTURE', 14, true, true);
        addWrappedText(sermon.scripture, 11);
        addSpacer(6);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Introduction
      if (sermon.introduction) {
        addWrappedText('INTRODUCTION', 14, true, true);
        addWrappedText(sermon.introduction, 11);
        addSpacer(6);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Main Points
      if (sermon.mainPoints && Array.isArray(sermon.mainPoints)) {
        sermon.mainPoints.forEach((point, idx) => {
          if (point.title || point.content) {
            addWrappedText(`MAIN POINT ${idx + 1}`, 14, true, true);
            if (point.title) {
              addWrappedText(point.title, 12, true);
            }
            if (point.content) {
              addWrappedText(point.content, 11);
            }
            if (point.verse) {
              addWrappedText(`Scripture: ${point.verse}`, 10, false);
            }
            addSpacer(6);
          }
        });
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Practical Application
      if (sermon.application) {
        addWrappedText('PRACTICAL APPLICATION', 14, true, true);
        addWrappedText(sermon.application, 11);
        addSpacer(6);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Conclusion
      if (sermon.conclusion) {
        addWrappedText('CONCLUSION', 14, true, true);
        addWrappedText(sermon.conclusion, 11);
        addSpacer(6);
        doc.line(margin, yPos, pageWidth - margin, yPos);
        yPos += 8;
      }

      // Closing Prayer
      if (sermon.prayer) {
        addWrappedText('CLOSING PRAYER', 14, true, true);
        addWrappedText(sermon.prayer, 11);
        addSpacer(10);
      }

      // Footer
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.text('Generated by FaithLight — faithlight.app', pageWidth / 2, pageHeight - 10, {
        align: 'center',
      });

      // Save
      doc.save(`${sermon.title || 'sermon'}.pdf`);
    } catch (err) {
      console.error('PDF generation error:', err);
      alert('Failed to generate PDF');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={loading || !sermon}
      className="min-h-[44px] min-w-[44px] flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 disabled:opacity-50 transition-all"
      aria-label="Download sermon as PDF"
    >
      <FileText size={18} />
      {loading ? 'Generating...' : 'Download PDF'}
    </button>
  );
}