import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import { Download, Image as ImageIcon, Loader2 } from 'lucide-react';

/**
 * Sermon export component - PDF and social media image templates
 */
export default function SermonExporter({ sermonText, sermonTitle, passage }) {
  const [exporting, setExporting] = useState(false);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = margin;

      // Title
      doc.setFontSize(18);
      doc.setFont(undefined, 'bold');
      const titleSplit = doc.splitTextToSize(sermonTitle, maxWidth);
      titleSplit.forEach((line) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 8;
      });

      // Passage reference
      yPosition += 5;
      doc.setFontSize(10);
      doc.setFont(undefined, 'italic');
      doc.text(`Passage: ${passage}`, margin, yPosition);
      yPosition += 8;

      // Separator line
      doc.setDrawColor(200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;

      // Sermon content
      doc.setFontSize(11);
      doc.setFont(undefined, 'normal');
      const contentSplit = doc.splitTextToSize(sermonText, maxWidth);
      contentSplit.forEach((line) => {
        if (yPosition > pageHeight - margin - 10) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 5;
      });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by FaithLight', margin, pageHeight - 8);

      doc.save(`sermon-${sermonTitle.replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setExporting(false);
    }
  };

  const exportToSocialImage = async () => {
    setExporting(true);
    try {
      const canvas = document.createElement('canvas');
      canvas.width = 1080;
      canvas.height = 1350;
      const ctx = canvas.getContext('2d');

      // Gradient background
      const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
      gradient.addColorStop(0, '#667eea');
      gradient.addColorStop(1, '#764ba2');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Title
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 48px Inter, sans-serif';
      ctx.textAlign = 'center';
      const titleLines = wrapText(ctx, sermonTitle, 900);
      let yPos = 150;
      titleLines.forEach((line) => {
        ctx.fillText(line, canvas.width / 2, yPos);
        yPos += 60;
      });

      // Passage
      yPos += 40;
      ctx.font = '28px italic Inter, sans-serif';
      ctx.fillStyle = '#e0e7ff';
      ctx.fillText(passage, canvas.width / 2, yPos);

      // FaithLight branding
      yPos = canvas.height - 80;
      ctx.font = 'bold 32px Inter, sans-serif';
      ctx.fillStyle = '#ffffff';
      ctx.fillText('FaithLight', canvas.width / 2, yPos);
      ctx.font = '20px Inter, sans-serif';
      ctx.fillStyle = '#e0e7ff';
      ctx.fillText('Sermon Preparation Made Easy', canvas.width / 2, yPos + 40);

      // Download
      const link = document.createElement('a');
      link.href = canvas.toDataURL('image/png');
      link.download = `sermon-${sermonTitle.replace(/\s+/g, '-')}-social.png`;
      link.click();
    } catch (err) {
      console.error('Social image export failed:', err);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="flex gap-2 flex-wrap">
      <button
        onClick={exportToPDF}
        disabled={exporting}
        className="flex items-center gap-2 px-4 py-2.5 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50 text-sm font-medium transition-colors min-h-[44px] disabled:opacity-50"
      >
        {exporting ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
        Export PDF
      </button>

      <button
        onClick={exportToSocialImage}
        disabled={exporting}
        className="flex items-center gap-2 px-4 py-2.5 rounded-lg border border-blue-300 text-blue-600 hover:bg-blue-50 text-sm font-medium transition-colors min-h-[44px] disabled:opacity-50"
      >
        {exporting ? <Loader2 size={16} className="animate-spin" /> : <ImageIcon size={16} />}
        Social Image
      </button>
    </div>
  );
}

// Helper to wrap text for canvas
function wrapText(ctx, text, maxWidth) {
  const words = text.split(' ');
  const lines = [];
  let currentLine = '';

  words.forEach((word) => {
    const testLine = currentLine + (currentLine ? ' ' : '') + word;
    if (ctx.measureText(testLine).width > maxWidth && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  });

  if (currentLine) lines.push(currentLine);
  return lines;
}